/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-03 00:11:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.semi.board.model.vo.Board;
import java.util.List;
import com.semi.board.model.vo.PageInfo;
import com.semi.member.model.vo.Member;

public final class freeBoardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/board/../common/footer.jsp", Long.valueOf(1580687082435L));
    _jspx_dependants.put("/WEB-INF/views/board/../common/loginedHeader.jsp", Long.valueOf(1580688528282L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.semi.board.model.vo.PageInfo");
    _jspx_imports_classes.add("com.semi.member.model.vo.Member");
    _jspx_imports_classes.add("com.semi.board.model.vo.Board");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	List<Board> bList = (List<Board>)request.getAttribute("bList");
	PageInfo pInf = (PageInfo)request.getAttribute("pInf");
	String boardType = (String)request.getAttribute("boardType");
	
	String searchKey = request.getParameter("searchKey");
	String searchValue = request.getParameter("searchValue");
	
	String status = null;
	if(boardType.equals("F")){
		status = "F";
	}else if(boardType.equals("FSEARCH")){
		status = "FSEARCH";
	}
	
	int listCount = pInf.getListCount();
	int currentPage = pInf.getCurrentPage();
	int maxPage = pInf.getMaxPage();
	int startPage = pInf.getStartPage();
	int endPage = pInf.getEndPage();
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("/* header */\r\n");
      out.write("*{margin:0; padding:0;}\r\n");
      out.write("a{\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  color : #333333;\r\n");
      out.write("}\r\n");
      out.write("ul{\r\n");
      out.write("  list-style: none;\r\n");
      out.write("}\r\n");
      out.write("a:hover{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("#shadow{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  background-color: rgba(0,0,0,0.5);\r\n");
      out.write("  z-index: 800;\r\n");
      out.write("  display: none;\r\n");
      out.write("  cursor : pointer;\r\n");
      out.write("}\r\n");
      out.write("#header{\r\n");
      out.write("    background-color: #002d4c;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    z-index: 500;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    top:0;\r\n");
      out.write("    left:0;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap nav{\r\n");
      out.write("  margin-right: 8rem;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap nav div > ul > li{\r\n");
      out.write("  float: left;\r\n");
      out.write("  padding-left: 10px;\r\n");
      out.write("  margin-left: 75px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap nav div > ul > li:first-child{\r\n");
      out.write("  margin-left:0;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap nav div > ul > li > ul{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 38px;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  width: 155px;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  background-color: #024068;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap nav a:hover{\r\n");
      out.write("    color : #f15a25;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap nav a.menu-list{\r\n");
      out.write("    color : white;\r\n");
      out.write("    font-size : 18px;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap nav a.menu-list+ul{\r\n");
      out.write("  display: none;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap .logo-img{\r\n");
      out.write("  width: 75%;\r\n");
      out.write("  min-width: 120px;\r\n");
      out.write("}\r\n");
      out.write("a.sub-menu-list{\r\n");
      out.write(" font-size : 16px;\r\n");
      out.write(" color : white;\r\n");
      out.write("}\r\n");
      out.write(".mypage-btn{\r\n");
      out.write("  width: 12%;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  cursor: default;\r\n");
      out.write("}\r\n");
      out.write(".mypage-btn img{\r\n");
      out.write("  width: 45px;\r\n");
      out.write("  transition: all 0.3s;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".mypage-btn img:hover{\r\n");
      out.write("  opacity : 0.7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 좌측 마이페이지 부분 */\r\n");
      out.write("#mypage-nav{\r\n");
      out.write("  width: 280px;\r\n");
      out.write("  background-color: #002d4c;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  z-index: 900;\r\n");
      out.write("  padding-top: 30px;\r\n");
      out.write("  display: none;\r\n");
      out.write("  top:0;\r\n");
      out.write("  left:0;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .info-area{\r\n");
      out.write("  background-color: #ffffff;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  width: 80%;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("  padding: 50px 25px;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .info-area .profile-icon{\r\n");
      out.write("  width: 100px;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .info-area ul{\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .info-area ul li{\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .bell-setting-btn{\r\n");
      out.write("  float: right;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .bell-setting-btn img{\r\n");
      out.write("  width:30px;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .mypage-btn-list a{\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  display: block;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .mypage-btn-list a:hover{\r\n");
      out.write("  color :#f15a25;\r\n");
      out.write("}\r\n");
      out.write("/* 푸터 */\r\n");
      out.write("#footer{\r\n");
      out.write("  background-color: #55595c;\r\n");
      out.write("  padding: 20px 0;\r\n");
      out.write("}\r\n");
      out.write("#footer .footer-logo{\r\n");
      out.write("    width: 120px;\r\n");
      out.write("}\r\n");
      out.write("#footer .copyright{\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  line-height: 91.5px;\r\n");
      out.write("  margin-bottom: 0;\r\n");
      out.write("  margin-left : 30px;\r\n");
      out.write("}\r\n");
      out.write("/* 탑 버튼 */\r\n");
      out.write("#button-top{\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  bottom: 100px;\r\n");
      out.write("  right: 100px;\r\n");
      out.write("  display:none;\r\n");
      out.write("}\r\n");
      out.write("#button-top .top-btn{\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  background-color: #f15a25;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  line-height: 50px;\r\n");
      out.write("  border-radius: 50px;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 반응형 세부 수정사항 */\r\n");
      out.write("@media (max-width: 767px){ /*767px : 구조가 바뀌는 기준*/\r\n");
      out.write("  #logo-wrap{\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("  #header-wrap nav{\r\n");
      out.write("    margin-right: 0;\r\n");
      out.write("  }\r\n");
      out.write("  .mypage-btn{\r\n");
      out.write("    width: 9%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 7%;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    transform: translate(0, -50%);\r\n");
      out.write("  }\r\n");
      out.write("  #footer .footer-logo-wrap{\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("  #footer .copyright{\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("@media (max-width: 590px){\r\n");
      out.write("  #header-wrap nav div > ul > li{\r\n");
      out.write("    margin-left:30px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("/* 기본 CSS 적용 */\r\n");
      out.write("ul{list-style: none;}\r\n");
      out.write("img,fieldset{border:none;}\r\n");
      out.write("body,input{color : #333333 !important;}\r\n");
      out.write("input,select,img{vertical-align:middle;}\r\n");
      out.write("table\t{border-collapse:collapse;}\r\n");
      out.write("\r\n");
      out.write("html body .background-navy{\r\n");
      out.write("  background: #002d4c;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("html body .background-orange{\r\n");
      out.write("  background: #f15a25;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("html body .background-gray{\r\n");
      out.write("  background: #9e9e9e;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.navy-btn{\r\n");
      out.write("  background-color: #002d4c;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  border: none;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.orange-btn{\r\n");
      out.write("  background-color: #f15a25;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  border: none;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.navy-hover-btn{\r\n");
      out.write("  background: transparent;\r\n");
      out.write("  color: #002d4c;\r\n");
      out.write("  border: 1px solid #002d4c;\r\n");
      out.write("  transition: all 0.3s;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.navy-hover-btn:hover{\r\n");
      out.write("  background:  #002d4c;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.orange-hover-btn{\r\n");
      out.write("  background: transparent;\r\n");
      out.write("  color: #f15a25;\r\n");
      out.write("  border: 1px solid #f15a25;\r\n");
      out.write("  transition: all 0.3s;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.orange-hover-btn:hover{\r\n");
      out.write("  background:  #f15a25;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.gray-btn{\r\n");
      out.write("  background-color: #f15a25;\r\n");
      out.write("  color: #9e9e9e;\r\n");
      out.write("  border: none;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write("html body .content-seciton.orange-hover-background{\r\n");
      out.write("  background-color: #9e9e9e;\r\n");
      out.write("  color: #333333;\r\n");
      out.write("  transition: all 0.3s;\r\n");
      out.write("}    \r\n");
      out.write("html body .content-seciton.orange-hover-background:hover{\r\n");
      out.write("  background-color: #f15a25;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("}   \r\n");
      out.write("html body .form-control.input-comment{\r\n");
      out.write("  transition: all 0.3s;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.input-comment:focus{\r\n");
      out.write("  border-color: #f15a25;\r\n");
      out.write("  box-shadow: 0 0 0 0.2rem rgba(241,90,37,.25);\r\n");
      out.write("}\r\n");
      out.write("html body .content-title{\r\n");
      out.write("  text-align: initial;\r\n");
      out.write("  margin: 50px 0;\r\n");
      out.write("  font-size: 35px;\r\n");
      out.write("  border-bottom: 2px solid #333333;\r\n");
      out.write("  padding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write(".page-link:hover,\r\n");
      out.write(".page-link{\r\n");
      out.write("  color : #f15a25;\r\n");
      out.write("}\r\n");
      out.write(".page-item.active .page-link{\r\n");
      out.write("  background-color: #f15a25;\r\n");
      out.write("  border-color: #f15a25;\r\n");
      out.write("}\r\n");
      out.write(".page-link:focus{ \r\n");
      out.write("  box-shadow: 0 0 0 0.2rem rgba(241,90,37,.25);\r\n");
      out.write("}\r\n");
      out.write(".pagination{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  transform: translateX(-50%);\r\n");
      out.write("  bottom: -80px;\r\n");
      out.write("}\r\n");
      out.write("/* 반응형 세부 수정사항 */\r\n");
      out.write("@media (max-width: 767px){ /*767px : 구조가 바뀌는 기준*/\r\n");
      out.write("  .form-control{\r\n");
      out.write("    min-width : 90px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("/* 게시판 */\r\n");
      out.write("#container{\r\n");
      out.write("  margin: 200px 0 100px 0;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  min-height :505px;\r\n");
      out.write("}\r\n");
      out.write("#board-wrap .board-title{\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  margin-bottom : 50px;\r\n");
      out.write("}\r\n");
      out.write("#board-wrap #search-wrap{\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  margin-bottom: 30px;\r\n");
      out.write("  height: 45px;\r\n");
      out.write("  padding-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("#board-wrap #search-wrap>*{\r\n");
      out.write("  float: right;\r\n");
      out.write("}\r\n");
      out.write("#board-wrap .board-form select{\r\n");
      out.write("  width: 15%;\r\n");
      out.write("  margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("#board-wrap .board-form .input-content{\r\n");
      out.write("  width: 35%;\r\n");
      out.write("  margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("#board-wrap .board-form .orange-btn-style{\r\n");
      out.write("  width: 7%;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write("#board-wrap .board-form .board{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  border: 1px solid #efefef;\r\n");
      out.write("  margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("#board-wrap .board-form .board thead tr{\r\n");
      out.write("  background-color: #002d4c;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  height: 40px;\r\n");
      out.write("}\r\n");
      out.write("#board-wrap .board-form .board tbody tr:hover:not(.no-list-tr){\r\n");
      out.write("  background-color : rgba(0,123,255,.25);\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("#board-wrap .board-form .board tbody tr{\r\n");
      out.write("  height: 35px;\r\n");
      out.write("  border-bottom: 1px solid #efefef;\r\n");
      out.write("}\r\n");
      out.write("#board-wrap .board-form .board th:first-child{\r\n");
      out.write("  width: 10%;\r\n");
      out.write("}\r\n");
      out.write("#board-wrap .board-form .board th:nth-child(2){\r\n");
      out.write("  width: 55%;\r\n");
      out.write("}\r\n");
      out.write("#board-wrap .board-form .board th:nth-child(3){\r\n");
      out.write("  width: 20%;\r\n");
      out.write("}\r\n");
      out.write("#board-wrap .board-form .board th:last-child{\r\n");
      out.write("  width: 15%;\r\n");
      out.write("}\r\n");
      out.write("#board-wrap .board-form  .write-content-btn{\r\n");
      out.write("  padding: .375rem 0;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  bottom: -20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 부트스트랩 색상 조정*/\r\n");
      out.write(".page-link:hover,\r\n");
      out.write(".page-link{\r\n");
      out.write("  color : #f15a25;\r\n");
      out.write("}\r\n");
      out.write(".page-item.active .page-link{\r\n");
      out.write("  background-color: #f15a25;\r\n");
      out.write("  border-color: #f15a25;\r\n");
      out.write("}\r\n");
      out.write(".form-control:focus,\r\n");
      out.write(".page-link:focus{\r\n");
      out.write("  box-shadow: 0 0 0 0.2rem rgba(241,90,37,.25);\r\n");
      out.write("}\r\n");
      out.write(".form-control:focus{\r\n");
      out.write("  border-color : #f15a25;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 767px){\r\n");
      out.write("  #board-wrap .board-form .orange-btn-style{\r\n");
      out.write("    width: 10%;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write(".no-has-list{\r\n");
      out.write("\tdisplay:none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member) session.getAttribute("loginMember");
	if(loginMember == null){
		System.out.println("세션 만료 실행");
		session.setAttribute("msg", "세션이 만료되어 메인페이지로 돌아갑니다.");
		response.sendRedirect(request.getContextPath());
	}
	
	int[] follow = (int[])session.getAttribute("follow");
	String memberImagePath = (String)session.getAttribute("memberImagePath");
	String profileImagePath = "/images/navi-icon-default.png"; // default 이미지 경로
	String msg = (String)session.getAttribute("msg");
	
	// null이 아니면 받아온 이미지 경로로 변경
	if(memberImagePath != null) profileImagePath = memberImagePath;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("\tintegrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"../images/favicon.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"../images/icon57.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"../images/icon114.png\">\r\n");
      out.write("<script>\r\n");
      out.write("\t");
 if(msg != null) {
      out.write("\r\n");
      out.write("\t\talert(\"");
      out.print( msg );
      out.write("\");\r\n");
      out.write("\t\t");
 session.removeAttribute("msg"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
 } 
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/common.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap icon link -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/76b49c6d9b.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\" class='m-0'>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"d-flex flex-column flex-md-row align-items-center mb-3 mt-3\"\r\n");
      out.write("\t\t\t\t\tid=\"header-wrap\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"mypage-btn\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../images/mypage-icon.png\" alt=\"마이페이지 버튼\"></a>\r\n");
      out.write("\t\t\t\t\t<h1 class=\"my-0 mr-md-auto font-weight-normal text-white\"\r\n");
      out.write("\t\t\t\t\t\tid=\"logo-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/main\"> <img class=\"logo-img\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"../images/logo2-white.png\" alt=\"로고\" id=\"logo-img\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t<nav class=\"my-2 my-md-0\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"menu-list\">학습노트</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"sub-menu-list\">학습노트 검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"sub-menu-list\">학습노트 만들기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"menu-list\">온스터디</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"sub-menu-list\">온스터디 검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"sub-menu-list\">온스터디 만들기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"sub-menu-list\">온스터디 인증하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"sub-menu-list\">온스터디 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/board/freeBoardList?boardType=F\" class=\"menu-list\">게시판</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/board/freeBoardList?boardType=F\" class=\"sub-menu-list\">자유 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/board/declareBoardList?boardType=SD\" class=\"sub-menu-list\">건의/신고 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//헤더 메뉴 호버 이벤트\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\".menu>li\").on({\r\n");
      out.write("\t\t\t\tmouseenter : function() {\r\n");
      out.write("\t\t\t\t\t$(this).find(\"ul\").stop().slideDown(300);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tmouseleave : function() {\r\n");
      out.write("\t\t\t\t\t$(this).find(\"ul\").stop().slideUp(300);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div id=\"mypage-nav\">\r\n");
      out.write("\t\t<div class=\"info-area\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath() + profileImagePath );
      out.write("\" alt=\"회원아이콘\"\r\n");
      out.write("\t\t\t\tclass=\"profile-icon\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>");
      out.print(loginMember.getMemberId() );
      out.write(" 님</li>\r\n");
      out.write("\t\t\t\t<li>");
      out.print(loginMember.getMemberPoint() );
      out.write(" 포인트</li>\r\n");
      out.write("\t\t\t\t<li>팔로워 수 : <span id=\"mypage-follower\">");
      out.print(follow[1] );
      out.write("</span>명</li>\r\n");
      out.write("\t\t\t\t<li>팔로잉 수 : <span id=\"mypage-following\">");
      out.print(follow[0] );
      out.write("</span>명</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"bell-setting-btn\">\r\n");
      out.write("\t\t\t\t<img src=\"../images/bell-off.png\" alt=\"알람벨버튼\"></a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/mypage\"\tclass=\"bell-setting-btn\">\r\n");
      out.write("\t\t\t\t<img src=\"../images/setting-off.png\" alt=\"세팅버튼\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"mypage-btn-list\">\r\n");
      out.write("\t\t\t<a href=\"#\">학습노트 관리</a>\r\n");
      out.write("\t\t\t<a href=\"#\">온스터디 내역</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/logout\">로그아웃</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"shadow\"></div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//좌측 마이페이지 버튼 클릭시 이벤트\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\".mypage-btn>img\").on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\t$(\"#mypage-nav\").fadeIn(300);\r\n");
      out.write("\t\t\t\t\t$(\"#shadow\").show(0);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#shadow\").on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\t$(this).hide(0);\r\n");
      out.write("\t\t\t\t\t$(\"#mypage-nav\").fadeOut(300);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 미니버튼 호버시 색상변경 이벤트\r\n");
      out.write("\t\t\t$(\".bell-setting-btn\").on(\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tmouseenter : function() {\r\n");
      out.write("\t\t\t\t\t\t\tvar renameImg = $(this).find(\"img\").prop(\"src\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.replace(\"-off.\", \"-on.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(this).find(\"img\").prop(\"src\", renameImg);\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tmouseleave : function() {\r\n");
      out.write("\t\t\t\t\t\t\tvar renameImg = $(this).find(\"img\").prop(\"src\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.replace(\"-on.\", \"-off.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(this).find(\"img\").prop(\"src\", renameImg);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"button-top\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"top-btn\">TOP</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction scrollFunction() {\r\n");
      out.write("\t\t\tif ($(window).scrollTop() >= 200) {\r\n");
      out.write("\t\t\t\t$('#button-top').show(0);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#button-top').hide(0);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tscrollFunction();\r\n");
      out.write("\t\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t\t\tscrollFunction();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('#button-top').on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\t$('html,body').stop().animate({\r\n");
      out.write("\t\t\t\t\t\tscrollTop : 0\r\n");
      out.write("\t\t\t\t\t}, 600);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 게시판 container start-->\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t          <div class=\"container\">\r\n");
      out.write("\t            <div class=\"row\">\r\n");
      out.write("\t              <div id=\"board-wrap\" class=\"col-md-12\">\r\n");
      out.write("\t              \t<h2 class=\"content-title\">자유 게시판</h2>\r\n");
      out.write("\t                <div class=\"board-content\">\r\n");
      out.write("\t                  <form action=\"");
      out.print( request.getContextPath() );
      out.write("/board/freeBoardList?boardType=FSEARCH\" method=\"post\" class=\"board-form\" onsubmit=\"return checkSearchVal();\"> \r\n");
      out.write("\t                    <div id=\"search-wrap\">                  \r\n");
      out.write("\t                      <button type=\"submit\" id=\"findContentBtn\"class=\"find-btn form-control orange-btn-style orange-hover-btn\">검색</button>\r\n");
      out.write("\t                      <input type=\"text\" id=\"searchValue\" class=\"form-control input-content\" placeholder=\"내용을 검색해주세요.\" name=\"searchValue\">\r\n");
      out.write("\t                      <select class=\"form-control\" name=\"searchKey\" id=\"searchKey\">\r\n");
      out.write("\t                        <option value=\"title\">제목</option>\r\n");
      out.write("\t                        <option value=\"writer\">작성자</option>\r\n");
      out.write("\t                        <option value=\"content\">내용</option>\r\n");
      out.write("\t                      </select>\r\n");
      out.write("\t                    </div>    \r\n");
      out.write("\t                      <div class=\"col-md-12\">\r\n");
      out.write("\t                        <div class=\"row\"> \r\n");
      out.write("\t                          <table class=\"board free-board\">\r\n");
      out.write("\t                            <thead>\r\n");
      out.write("\t                              <tr>\r\n");
      out.write("\t                                <th>No</th>\r\n");
      out.write("\t                                <th>제목</th>\r\n");
      out.write("\t                                <th>작성자</th>\r\n");
      out.write("\t                                <th>작성일</th>\r\n");
      out.write("\t                              </tr>\r\n");
      out.write("\t                            </thead>\r\n");
      out.write("\t                            <tbody>\r\n");
      out.write("\t                              ");
 if(bList.isEmpty()){ 
      out.write("        \r\n");
      out.write("\t                              <tr class=\"no-list-tr\">\r\n");
      out.write("\t                              \t<td colspan=\"5\"  class=\"nolist-warning\">존재하는 게시글이 없습니다.</td>\r\n");
      out.write("\t                              </tr>\r\n");
      out.write("\t                              ");
 }else{ 
      out.write("\r\n");
      out.write("\t                              \t");
 for(Board board : bList){
      out.write("\r\n");
      out.write("\t                              \t\t<tr>\r\n");
      out.write("\t                              \t\t\t<td class=\"no-has-list\">");
      out.print( board.getBoardNo());
      out.write("</td>\r\n");
      out.write("\t                              \t\t\t<td class=\"has-list\">");
      out.print( board.getBoardNumbering());
      out.write("</td>\r\n");
      out.write("\t                              \t\t\t<td class=\"has-list\">");
      out.print( board.getBoardTitle());
      out.write("</td>\r\n");
      out.write("\t                              \t\t\t<td class=\"has-list\">");
      out.print( board.getBoardWriter());
      out.write("</td>\r\n");
      out.write("\t                              \t\t\t<td class=\"has-list\">");
      out.print( board.getBoardModifyDt());
      out.write("</td>\r\n");
      out.write("\t                              \t\t\t\r\n");
      out.write("\t                              \t");
 } 
      out.write("\r\n");
      out.write("\t                              ");
 } 
      out.write("\r\n");
      out.write("\t                            </tbody>\r\n");
      out.write("\t                          </table>\r\n");
      out.write("\t                          <a href=\"");
      out.print( request.getContextPath() );
      out.write("/board/goInsertFreeBoard\" class=\"write-content-btn form-control orange-hover-btn orange-btn-style\">글쓰기</a>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                      </div>\r\n");
      out.write("\t                      <ul class=\"pagination\">\r\n");
      out.write("\t                      \t");
 if(currentPage>1){
      out.write("\r\n");
      out.write("\t                        <li class=\"page-item\">\r\n");
      out.write("\t                          <a class=\"page-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/board/freeBoardList?boardType=");
      out.print( status );
      out.write("&currentPage=1&searchKey=");
      out.print( searchKey );
      out.write("&searchValue=");
      out.print( searchValue );
      out.write("\">&lt;&lt;</a>\r\n");
      out.write("\t                        </li>\r\n");
      out.write("\t                        <li class=\"page-item\">\r\n");
      out.write("\t                          <a class=\"page-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/board/freeBoardList?boardType=");
      out.print( status );
      out.write("&currentPage=");
      out.print( currentPage-1 );
      out.write("&searchKey=");
      out.print( searchKey );
      out.write("&searchValue=");
      out.print( searchValue );
      out.write("\">&lt;</a>\r\n");
      out.write("\t                        </li>\r\n");
      out.write("\t                        ");
 } 
      out.write("\r\n");
      out.write("\t                        \r\n");
      out.write("\t                        ");
 for(int p = startPage; p <= endPage; p++){ 
      out.write("\r\n");
      out.write("\t                        \t");
 if(p == currentPage) { 
      out.write("\r\n");
      out.write("\t\t\t                        <li class=\"page-item active\">\r\n");
      out.write("\t\t\t                          <a class=\"page-link\">");
      out.print( p );
      out.write("</a>\r\n");
      out.write("\t\t\t                        </li>\r\n");
      out.write("\t\t\t                    ");
 }else{
      out.write("\r\n");
      out.write("\t\t\t                    \t<li class=\"page-item\">\r\n");
      out.write("\t\t\t                          <a class=\"page-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/board/freeBoardList?boardType=");
      out.print( status );
      out.write("&currentPage=");
      out.print( p );
      out.write("&searchKey=");
      out.print( searchKey );
      out.write("&searchValue=");
      out.print( searchValue );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
      out.write("\t\t\t                        </li>\r\n");
      out.write("\t                        \t");
 }
      out.write("\r\n");
      out.write("                        \t");
 }
      out.write("\r\n");
      out.write("                        \t\r\n");
      out.write("\t                        ");
 if(currentPage<maxPage){
      out.write("\r\n");
      out.write("\t                        <li class=\"page-item\">\r\n");
      out.write("\t                          <a class=\"page-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/board/freeBoardList?boardType=");
      out.print( status );
      out.write("&currentPage=");
      out.print( currentPage+1 );
      out.write("&searchKey=");
      out.print( searchKey );
      out.write("&searchValue=");
      out.print( searchValue );
      out.write("\">&gt;</a>\r\n");
      out.write("\t                        </li>\r\n");
      out.write("\t                        <li class=\"page-item\">\r\n");
      out.write("\t                          <a class=\"page-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/board/freeBoardList?boardType=");
      out.print( status );
      out.write("&currentPage=");
      out.print( maxPage );
      out.write("&searchKey=");
      out.print( searchKey );
      out.write("&searchValue=");
      out.print( searchValue );
      out.write("\">&gt;&gt;</a>\r\n");
      out.write("\t                        </li>\r\n");
      out.write("\t                        ");
 } 
      out.write("\r\n");
      out.write("\t                      </ul>\r\n");
      out.write("\t                    </form>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <!-- 게시판 container end-->\r\n");
      out.write("\t        ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("        <div class=\"container-fluid container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4 footer-logo-wrap\">\r\n");
      out.write("                            <img class=\"footer-logo\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/logo2-white.png\" alt=\"푸터로고\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-8\">\r\n");
      out.write("                            <p class=\"copyright\">&copy; 2020 NOKJO COMPANY. ALL RIGHTS RESERVED.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\t   \r\n");
      out.write("\t        \r\n");
      out.write("\t        <script>\r\n");
      out.write("\t        \t$(function(){\r\n");
      out.write("\t        \t\t\r\n");
      out.write("\t\t        \t/* 게시글 상세 조회용  */\r\n");
      out.write("\t        \t\t$(\".free-board .has-list\").on({\r\n");
      out.write("\t        \t\t\tclick : function(){\r\n");
      out.write("\t        \t\t\t\tvar boardNo = $(this).parent().children().eq(0).text();\r\n");
      out.write("\t        \t\t\t\tvar boardNumbering = $(this).parent().children().eq(1).text();\r\n");
      out.write("\t        \t\t\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/board/freeBoardDetail?no=\"+boardNo +\"&Numbering=\"+boardNumbering+\"&currentPage=\"+");
      out.print(currentPage);
      out.write(";\r\n");
      out.write("\t        \t\t\t}\r\n");
      out.write("\t        \t\t});\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        \t/* 검색용 */\r\n");
      out.write("\t        \t\tvar searchKey = \"");
      out.print( searchKey );
      out.write("\";\r\n");
      out.write("            \t\tvar searchValue = \"");
      out.print( searchValue );
      out.write("\";\r\n");
      out.write("            \t\t\r\n");
      out.write("            \t\tif(searchKey != \"null\" && searchValue != \"null\"){\r\n");
      out.write("            \t\t\t// 검색한 경우\r\n");
      out.write("            \t\t\t$.each( $(\"select[name=searchKey] > option\"), function(index,item){\r\n");
      out.write("            \t\t\t\tif($(item).val() == searchKey){\r\n");
      out.write("            \t\t\t\t\t//$(item) : 현재 접근 요소\r\n");
      out.write("\t\t\t\t\t\t\t\t$(item).prop(\"selected\",\"true\");\t            \t\t\t\t\t\r\n");
      out.write("            \t\t\t\t}\r\n");
      out.write("            \t\t\t});\r\n");
      out.write("            \t\t\t$(\"input[name=searchValue]\").val(searchValue);\r\n");
      out.write("            \t\t}\r\n");
      out.write("            \t\t\r\n");
      out.write("            \t\t\r\n");
      out.write("\t        \t});\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        \t// 검색내용없이 검색했을때 다시 첫 페이지로 이동\r\n");
      out.write("\t        \tfunction checkSearchVal(){\r\n");
      out.write("\t        \t\tconsole.log($(\"#searchKey\").val());\r\n");
      out.write("\t        \t\tconsole.log($(\"#searchValue\").val());\r\n");
      out.write("\t        \t\t\r\n");
      out.write("\t        \t\tif($(\"#searchValue\").val().length==0){\r\n");
      out.write("\t        \t\t\tlocation.href=\"freeBoardList?boardType=F\";\r\n");
      out.write("\t\t        \t\treturn false;\r\n");
      out.write("\t        \t\t}\r\n");
      out.write("\t\t\t\t\treturn true;\t        \t\t\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        </script>     \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
