/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-03 02:57:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.semi.board.model.vo.Board;
import com.semi.board.model.vo.BoardImage;
import java.util.ArrayList;
import com.semi.member.model.vo.Member;

public final class updateFreeBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/board/../common/footer.jsp", Long.valueOf(1580687082435L));
    _jspx_dependants.put("/WEB-INF/views/board/../common/loginedHeader.jsp", Long.valueOf(1580698249394L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.semi.board.model.vo.BoardImage");
    _jspx_imports_classes.add("com.semi.member.model.vo.Member");
    _jspx_imports_classes.add("com.semi.board.model.vo.Board");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Board board = (Board)request.getAttribute("board");
	ArrayList<BoardImage> files = (ArrayList<BoardImage>)request.getAttribute("files");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>온스터디</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* header */\r\n");
      out.write("*{margin:0; padding:0;}\r\n");
      out.write("a{\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  color : #333333;\r\n");
      out.write("}\r\n");
      out.write("ul{\r\n");
      out.write("  list-style: none;\r\n");
      out.write("}\r\n");
      out.write("a:hover{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("#shadow{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  background-color: rgba(0,0,0,0.5);\r\n");
      out.write("  z-index: 800;\r\n");
      out.write("  display: none;\r\n");
      out.write("  cursor : pointer;\r\n");
      out.write("}\r\n");
      out.write("#header{\r\n");
      out.write("    background-color: #002d4c;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    z-index: 500;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    top:0;\r\n");
      out.write("    left:0;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap nav{\r\n");
      out.write("  margin-right: 8rem;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap nav div > ul > li{\r\n");
      out.write("  float: left;\r\n");
      out.write("  padding-left: 10px;\r\n");
      out.write("  margin-left: 75px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap nav div > ul > li:first-child{\r\n");
      out.write("  margin-left:0;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap nav div > ul > li > ul{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 38px;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  width: 155px;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  background-color: #024068;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap nav a:hover{\r\n");
      out.write("    color : #f15a25;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap nav a.menu-list{\r\n");
      out.write("    color : white;\r\n");
      out.write("    font-size : 18px;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap nav a.menu-list+ul{\r\n");
      out.write("  display: none;\r\n");
      out.write("}\r\n");
      out.write("#header-wrap .logo-img{\r\n");
      out.write("  width: 75%;\r\n");
      out.write("  min-width: 120px;\r\n");
      out.write("}\r\n");
      out.write("a.sub-menu-list{\r\n");
      out.write(" font-size : 16px;\r\n");
      out.write(" color : white;\r\n");
      out.write("}\r\n");
      out.write(".mypage-btn{\r\n");
      out.write("  width: 12%;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  cursor: default;\r\n");
      out.write("}\r\n");
      out.write(".mypage-btn img{\r\n");
      out.write("  width: 45px;\r\n");
      out.write("  transition: all 0.3s;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".mypage-btn img:hover{\r\n");
      out.write("  opacity : 0.7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 좌측 마이페이지 부분 */\r\n");
      out.write("#mypage-nav{\r\n");
      out.write("  width: 280px;\r\n");
      out.write("  background-color: #002d4c;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  z-index: 900;\r\n");
      out.write("  padding-top: 30px;\r\n");
      out.write("  display: none;\r\n");
      out.write("  top:0;\r\n");
      out.write("  left:0;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .info-area{\r\n");
      out.write("  background-color: #ffffff;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  width: 80%;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("  padding: 50px 25px;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .info-area .profile-icon{\r\n");
      out.write("  width: 100px;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .info-area ul{\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .info-area ul li{\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .bell-setting-btn{\r\n");
      out.write("  float: right;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .bell-setting-btn img{\r\n");
      out.write("  width:30px;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .mypage-btn-list a{\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  display: block;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("#mypage-nav .mypage-btn-list a:hover{\r\n");
      out.write("  color :#f15a25;\r\n");
      out.write("}\r\n");
      out.write("/* 푸터 */\r\n");
      out.write("#footer{\r\n");
      out.write("  background-color: #55595c;\r\n");
      out.write("  padding: 20px 0;\r\n");
      out.write("}\r\n");
      out.write("#footer .footer-logo{\r\n");
      out.write("    width: 120px;\r\n");
      out.write("}\r\n");
      out.write("#footer .copyright{\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  line-height: 91.5px;\r\n");
      out.write("  margin-bottom: 0;\r\n");
      out.write("  margin-left : 30px;\r\n");
      out.write("}\r\n");
      out.write("/* 탑 버튼 */\r\n");
      out.write("#button-top{\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  bottom: 100px;\r\n");
      out.write("  right: 100px;\r\n");
      out.write("  display:none;\r\n");
      out.write("}\r\n");
      out.write("#button-top .top-btn{\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  background-color: #f15a25;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  line-height: 50px;\r\n");
      out.write("  border-radius: 50px;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 반응형 세부 수정사항 */\r\n");
      out.write("@media (max-width: 767px){ /*767px : 구조가 바뀌는 기준*/\r\n");
      out.write("  #logo-wrap{\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("  #header-wrap nav{\r\n");
      out.write("    margin-right: 0;\r\n");
      out.write("  }\r\n");
      out.write("  .mypage-btn{\r\n");
      out.write("    width: 9%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 7%;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    transform: translate(0, -50%);\r\n");
      out.write("  }\r\n");
      out.write("  #footer .footer-logo-wrap{\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("  #footer .copyright{\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("@media (max-width: 590px){\r\n");
      out.write("  #header-wrap nav div > ul > li{\r\n");
      out.write("    margin-left:30px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("/* 기본 CSS 적용 */\r\n");
      out.write("ul{list-style: none;}\r\n");
      out.write("img,fieldset{border:none;}\r\n");
      out.write("body,input{color : #333333 !important;}\r\n");
      out.write("input,select,img{vertical-align:middle;}\r\n");
      out.write("table\t{border-collapse:collapse;}\r\n");
      out.write("\r\n");
      out.write("html body .background-navy{\r\n");
      out.write("  background: #002d4c;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("html body .background-orange{\r\n");
      out.write("  background: #f15a25;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("html body .background-gray{\r\n");
      out.write("  background: #9e9e9e;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.navy-btn{\r\n");
      out.write("  background-color: #002d4c;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  border: none;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.orange-btn{\r\n");
      out.write("  background-color: #f15a25;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  border: none;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.navy-hover-btn{\r\n");
      out.write("  background: transparent;\r\n");
      out.write("  color: #002d4c;\r\n");
      out.write("  border: 1px solid #002d4c;\r\n");
      out.write("  transition: all 0.3s;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.navy-hover-btn:hover{\r\n");
      out.write("  background:  #002d4c;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.orange-hover-btn{\r\n");
      out.write("  background: transparent;\r\n");
      out.write("  color: #f15a25;\r\n");
      out.write("  border: 1px solid #f15a25;\r\n");
      out.write("  transition: all 0.3s;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.orange-hover-btn:hover{\r\n");
      out.write("  background:  #f15a25;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.gray-btn{\r\n");
      out.write("  background-color: #f15a25;\r\n");
      out.write("  color: #9e9e9e;\r\n");
      out.write("  border: none;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write("html body .content-seciton.orange-hover-background{\r\n");
      out.write("  background-color: #9e9e9e;\r\n");
      out.write("  color: #333333;\r\n");
      out.write("  transition: all 0.3s;\r\n");
      out.write("}    \r\n");
      out.write("html body .content-seciton.orange-hover-background:hover{\r\n");
      out.write("  background-color: #f15a25;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("}   \r\n");
      out.write("html body .form-control.input-comment{\r\n");
      out.write("  transition: all 0.3s;\r\n");
      out.write("}\r\n");
      out.write("html body .form-control.input-comment:focus{\r\n");
      out.write("  border-color: #f15a25;\r\n");
      out.write("  box-shadow: 0 0 0 0.2rem rgba(241,90,37,.25);\r\n");
      out.write("}\r\n");
      out.write("html body .content-title{\r\n");
      out.write("  text-align: initial;\r\n");
      out.write("  margin: 50px 0;\r\n");
      out.write("  font-size: 35px;\r\n");
      out.write("  border-bottom: 2px solid #333333;\r\n");
      out.write("  padding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write(".page-link:hover,\r\n");
      out.write(".page-link{\r\n");
      out.write("  color : #f15a25;\r\n");
      out.write("}\r\n");
      out.write(".page-item.active .page-link{\r\n");
      out.write("  background-color: #f15a25;\r\n");
      out.write("  border-color: #f15a25;\r\n");
      out.write("}\r\n");
      out.write(".page-link:focus{ \r\n");
      out.write("  box-shadow: 0 0 0 0.2rem rgba(241,90,37,.25);\r\n");
      out.write("}\r\n");
      out.write(".pagination{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  transform: translateX(-50%);\r\n");
      out.write("  bottom: -80px;\r\n");
      out.write("}\r\n");
      out.write("/* 반응형 세부 수정사항 */\r\n");
      out.write("@media (max-width: 767px){ /*767px : 구조가 바뀌는 기준*/\r\n");
      out.write("  .form-control{\r\n");
      out.write("    min-width : 90px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("/* 게시판 작성용 css */\r\n");
      out.write("#container{\r\n");
      out.write("  margin: 200px 0 100px 0;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("#board-write-wrap .board-title{\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  margin-bottom : 50px;\r\n");
      out.write("}\r\n");
      out.write(".warning{\r\n");
      out.write("  text-align: end;\r\n");
      out.write("  color: #ee4135;\r\n");
      out.write("  margin : 5px 0;\r\n");
      out.write("}\r\n");
      out.write(".board-write table{\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".board-write table th{\r\n");
      out.write("  width: 20%;\r\n");
      out.write("  background: #002d4c;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  border-radius: .25rem;\r\n");
      out.write("}\r\n");
      out.write(".board-write .input-content{\r\n");
      out.write("    resize: none;\r\n");
      out.write("}\r\n");
      out.write(".file{\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("}\r\n");
      out.write(".board-write .submit-btn{\r\n");
      out.write("  background-color: #f15a25;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  border: none;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  width: 11%;\r\n");
      out.write("  margin-top: 15px;\r\n");
      out.write("  float: right;\r\n");
      out.write("}\r\n");
      out.write(".board-write .cancel-btn{\r\n");
      out.write("  float: right;\r\n");
      out.write("  background-color: #9e9e9e;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  margin-top: 15px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  width: 8%;\r\n");
      out.write("  float: right;\r\n");
      out.write("  line-height: 38px;\r\n");
      out.write("  margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("#board-write-wrap .form-control:focus:focus{\r\n");
      out.write("  border-color: #f15a25;\r\n");
      out.write("  box-shadow: 0 0 0 0.2rem rgba(241,90,37,.25);\r\n");
      out.write("}\r\n");
      out.write(".form-td img{\r\n");
      out.write("\tcursor : pointer;\r\n");
      out.write("}\r\n");
      out.write(".form-inline>.boardImg{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 130px;\r\n");
      out.write("    height: 130px;\r\n");
      out.write("}\r\n");
      out.write(".plese-upload{\r\n");
      out.write("\tposition : absolute;\r\n");
      out.write("\ttop : 50%;\r\n");
      out.write("\tleft : 50%; \r\n");
      out.write("\ttransform : translate(-50%,-50%);\r\n");
      out.write("\tcolor : #6c757d;\r\n");
      out.write("}\r\n");
      out.write(".mini-thumbnail-img{\r\n");
      out.write("\tposition : absolute;\r\n");
      out.write("\ttop : 0;\r\n");
      out.write("\tleft : 0;\r\n");
      out.write("}\r\n");
      out.write(".form-td{\r\n");
      out.write("    display: block;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border: 1px solid #ced4da;\r\n");
      out.write("    border-radius: .25rem;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member) session.getAttribute("loginMember");
	if(loginMember == null){
		System.out.println("세션 만료 실행");
		session.setAttribute("msg", "세션이 만료되어 메인페이지로 돌아갑니다.");
		response.sendRedirect(request.getContextPath());
	}
	
	int[] follow = (int[])session.getAttribute("follow");
	String memberImagePath = (String)session.getAttribute("memberImagePath");
	String profileImagePath = "/images/navi-icon-default.png"; // default 이미지 경로
	String msg = (String)session.getAttribute("msg");
	
	// null이 아니면 받아온 이미지 경로로 변경
	if(memberImagePath != null) profileImagePath = memberImagePath;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("\tintegrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/favicon.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/icon57.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/icon114.png\">\r\n");
      out.write("<script>\r\n");
      out.write("\t");
 if(msg != null) {
      out.write("\r\n");
      out.write("\t\talert(\"");
      out.print( msg );
      out.write("\");\r\n");
      out.write("\t\t");
 session.removeAttribute("msg"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
 } 
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/common.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap icon link -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/76b49c6d9b.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\" class='m-0'>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"d-flex flex-column flex-md-row align-items-center mb-3 mt-3\"\r\n");
      out.write("\t\t\t\t\tid=\"header-wrap\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"mypage-btn\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../images/mypage-icon.png\" alt=\"마이페이지 버튼\"></a>\r\n");
      out.write("\t\t\t\t\t<h1 class=\"my-0 mr-md-auto font-weight-normal text-white\"\r\n");
      out.write("\t\t\t\t\t\tid=\"logo-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/main\"> <img class=\"logo-img\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"../images/logo2-white.png\" alt=\"로고\" id=\"logo-img\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t<nav class=\"my-2 my-md-0\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"menu-list\">학습노트</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"sub-menu-list\">학습노트 검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"sub-menu-list\">학습노트 만들기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/onstudy/main\" class=\"menu-list\">온스터디</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/onstudy/main\" class=\"sub-menu-list\">온스터디 검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/onstudy/createView\" class=\"sub-menu-list\">온스터디 만들기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/onstudy/certify\" class=\"sub-menu-list\">온스터디 인증하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/onstudy/manage\" class=\"sub-menu-list\">온스터디 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/board/freeBoardList?boardType=F\" class=\"menu-list\">게시판</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/board/freeBoardList?boardType=F\" class=\"sub-menu-list\">자유 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/board/declareBoardList?boardType=SD\" class=\"sub-menu-list\">건의/신고 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//헤더 메뉴 호버 이벤트\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\".menu>li\").on({\r\n");
      out.write("\t\t\t\tmouseenter : function() {\r\n");
      out.write("\t\t\t\t\t$(this).find(\"ul\").stop().slideDown(300);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tmouseleave : function() {\r\n");
      out.write("\t\t\t\t\t$(this).find(\"ul\").stop().slideUp(300);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div id=\"mypage-nav\">\r\n");
      out.write("\t\t<div class=\"info-area\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath() + profileImagePath );
      out.write("\" alt=\"회원아이콘\"\r\n");
      out.write("\t\t\t\tclass=\"profile-icon\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>");
      out.print(loginMember.getMemberId() );
      out.write(" 님</li>\r\n");
      out.write("\t\t\t\t<li>");
      out.print(loginMember.getMemberPoint() );
      out.write(" 포인트</li>\r\n");
      out.write("\t\t\t\t<li>팔로워 수 : <span id=\"mypage-follower\">");
      out.print(follow[1] );
      out.write("</span>명</li>\r\n");
      out.write("\t\t\t\t<li>팔로잉 수 : <span id=\"mypage-following\">");
      out.print(follow[0] );
      out.write("</span>명</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"bell-setting-btn\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/bell-off.png\" alt=\"알람벨버튼\"></a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/mypage\"\tclass=\"bell-setting-btn\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/setting-off.png\" alt=\"세팅버튼\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"mypage-btn-list\">\r\n");
      out.write("\t\t\t<a href=\"#\">학습노트 관리</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/onstudyList\">온스터디 내역</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/logout\">로그아웃</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"shadow\"></div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//좌측 마이페이지 버튼 클릭시 이벤트\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\".mypage-btn>img\").on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\t$(\"#mypage-nav\").fadeIn(300);\r\n");
      out.write("\t\t\t\t\t$(\"#shadow\").show(0);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#shadow\").on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\t$(this).hide(0);\r\n");
      out.write("\t\t\t\t\t$(\"#mypage-nav\").fadeOut(300);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 미니버튼 호버시 색상변경 이벤트\r\n");
      out.write("\t\t\t$(\".bell-setting-btn\").on(\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tmouseenter : function() {\r\n");
      out.write("\t\t\t\t\t\t\tvar renameImg = $(this).find(\"img\").prop(\"src\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.replace(\"-off.\", \"-on.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(this).find(\"img\").prop(\"src\", renameImg);\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tmouseleave : function() {\r\n");
      out.write("\t\t\t\t\t\t\tvar renameImg = $(this).find(\"img\").prop(\"src\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.replace(\"-on.\", \"-off.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(this).find(\"img\").prop(\"src\", renameImg);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"button-top\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"top-btn\">TOP</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction scrollFunction() {\r\n");
      out.write("\t\t\tif ($(window).scrollTop() >= 200) {\r\n");
      out.write("\t\t\t\t$('#button-top').show(0);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#button-top').hide(0);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tscrollFunction();\r\n");
      out.write("\t\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t\t\tscrollFunction();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('#button-top').on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\t$('html,body').stop().animate({\r\n");
      out.write("\t\t\t\t\t\tscrollTop : 0\r\n");
      out.write("\t\t\t\t\t}, 600);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t<div id=\"container\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div id=\"board-write-wrap\" class=\"col-md-12\">\r\n");
      out.write("                <h2 class=\"content-title\">자유 게시판 수정하기</h2>\r\n");
      out.write("                <p class=\"warning\">비밀글은 신고/건의 카테고리에만 작성할 수 있습니다.</p>\r\n");
      out.write("                <p class=\"warning\">파일첨부는 최대 4개까지 가능합니다.</p>\r\n");
      out.write("                <div class=\"board-write\">\r\n");
      out.write("                  <form class=\"write-form\" action=\"");
      out.print( request.getContextPath() );
      out.write("/board/updateBoard?bNo=");
      out.print( board.getBoardNo());
      out.write("&secret=N\" \r\n");
      out.write("                  method=\"post\" enctype=\"multipart/form-data\" role=\"form\" onsubmit=\"return validate();\">\r\n");
      out.write("                    <table>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <th><label for=\"title\">제목</label></th>\r\n");
      out.write("                        <td class=\"form-td\"><input id=\"title\" value=\"");
      out.print( board.getBoardTitle());
      out.write("\"class=\"form-control input-title\" type=\"text\" name=\"title\" placeholder=\"제목을 입력해주세요.\"></td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <th><label for=\"content\">내용</label></th>\r\n");
      out.write("                        <td class=\"form-td\">\r\n");
      out.write("                          <textarea id=\"content\" class=\"form-control input-content\" name=\"content\" rows=\"15\" cols=\"100\" placeholder=\"내용을 입력해주세요.\">");
      out.print( board.getBoardContent());
      out.write("</textarea>\r\n");
      out.write("                        </td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                      \t<th><label for=\"file\">파일첨부</label></th>\r\n");
      out.write("                      \t<td class=\"form-td\">\r\n");
      out.write("                      \t\t<div class=\"form-inline\">\r\n");
      out.write("                      \t\t\r\n");
      out.write("                      \t\t<!-- 기본 첨부 이미지 세팅 -->\r\n");
      out.write("                      \t\t\t");
 if(files != null){ 
      out.write("\r\n");
      out.write("                      \t\t\t\t");
 for(int i=0; i<files.size() ; i++) {
	                      				String src = request.getContextPath()+"/resources/boardImages/"+files.get(i).getImageChangeName();
	                      			
      out.write("\r\n");
      out.write("                      \t\t\t\t<div class=\"mr-2 boardImg\" id=\"contentImgArea");
      out.print(i+1);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"plese-upload plese-upload");
      out.print(i+1 );
      out.write("\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"mini-thumbnail-img\" id=\"contentImg");
      out.print(i+1);
      out.write("\" width=\"130\" height=\"130\" src=\"");
      out.print(src );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonerror=\"this.src='../images/document.png'\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                      \t\t\t\t");
} 
      out.write("\r\n");
      out.write("                      \t\t\t\t");
if(files.size() < 4){ 
      out.write("\r\n");
      out.write("                      \t\t\t\t\t");
for(int j=files.size()+1 ; j<5; j++){ 
      out.write("\r\n");
      out.write("                      \t\t\t\t\t<div class=\"mr-2 boardImg\" id=\"contentImgArea");
      out.print(j);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"plese-upload plese-upload");
      out.print(j );
      out.write("\">클릭시 첨부</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img class=\"mini-thumbnail-img\" id=\"contentImg");
      out.print(j);
      out.write("\" width=\"130\" height=\"130\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                      \t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("                      \t\t\t\t");
} 
      out.write("\r\n");
      out.write("                      \t\t\t");
 }else{
      out.write("\r\n");
      out.write("                      \t\t\t\t");
for(int k=0; k<4; k++){ 
      out.write("\r\n");
      out.write("                      \t\t\t\t<div class=\"mr-2 boardImg\" id=\"contentImgArea");
      out.print(k+1);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"plese-upload plese-upload");
      out.print(k+1 );
      out.write("\">클릭시 첨부</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"mini-thumbnail-img\" id=\"contentImg");
      out.print(k+1);
      out.write("\" width=\"130\" height=\"130\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("                      \t\t\t");
} 
      out.write("\r\n");
      out.write("                      \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 파일 업로드 하는 부분 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"fileArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"file\" id=\"img1\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"img1\" onchange=\"LoadImg(this,1)\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"file\" id=\"img2\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"img2\" onchange=\"LoadImg(this,2)\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"file\" id=\"img3\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"img3\" onchange=\"LoadImg(this,3)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t <input type=\"file\" id=\"img4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"img4\" onchange=\"LoadImg(this,4)\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("                      \t</td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <button class=\"submit-btn form-control orange-hover-btn\" name=\"submit\">수정 완료</button>\r\n");
      out.write("                    <a class=\"cancel-btn form-control\" href=\"freeBoardList?boardType=F\">취소</a>\r\n");
      out.write("                    \r\n");
      out.write("                     <!-- 이미지 수정 하려고 클릭하면 값이 바뀌어서 수정 여부 판별 가능 -->\r\n");
      out.write("                    ");
if(files != null){ 
      out.write("\r\n");
      out.write("                    ");
 for(int i=0 ; i<4 ; i++){ 
		                  if(i < files.size()){ 
      out.write("\r\n");
      out.write("\t\t               \t\t<input type=\"hidden\" name=\"beforeImg\" value=\"");
      out.print( files.get(i).getImageChangeName());
      out.write("\">\r\n");
      out.write("\t\t               ");
 }else{
      out.write("\r\n");
      out.write("\t\t               \t\t<input type=\"hidden\" name=\"beforeImg\" value=\"\">\r\n");
      out.write("\t\t            ");
    } 
		           	   } 
      out.write("\r\n");
      out.write("\t\t           ");
} 
      out.write("\r\n");
      out.write("\t\t           \r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("        <div class=\"container-fluid container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4 footer-logo-wrap\">\r\n");
      out.write("                            <img class=\"footer-logo\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/logo2-white.png\" alt=\"푸터로고\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-8\">\r\n");
      out.write("                            <p class=\"copyright\">&copy; 2020 NOKJO COMPANY. ALL RIGHTS RESERVED.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <script>\t  \r\n");
      out.write("    \t\t// 유효성 검사\r\n");
      out.write("\t        function validate() {\r\n");
      out.write("    \t\t\t\r\n");
      out.write("\t        \t/* 이미지 수정 시 필요한 부분 */\r\n");
      out.write("        \t    $.each( $(\"input[type=file]\"), function(index, item){\r\n");
      out.write("                   \r\n");
      out.write("                   if($(item).val() == \"\"){\r\n");
      out.write("                      $($(\"input[name=beforeImg]\").get(index)).val(\"\");\r\n");
      out.write("                   }\r\n");
      out.write("                });\r\n");
      out.write("\t        \t\r\n");
      out.write("\t\t\t\tif ($(\"#title\").val().trim().length == 0) {\r\n");
      out.write("\t\t\t\t\talert(\"제목을 입력해 주세요.\");\r\n");
      out.write("\t\t\t\t\t$(\"#title\").focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\tif ($(\"#content\").val().trim().length == 0) {\r\n");
      out.write("\t\t\t\t\talert(\"내용을 입력해 주세요.\");\r\n");
      out.write("\t\t\t\t\t$(\"#content\").focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("        \t$(function(){\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\t// 이미지 공간을 클릭할 때 파일 첨부 창이 뜨도록 설정하는 함수\r\n");
      out.write("       \t    \t// 파일 선택 버튼이 있는 영역을 보이지 않게 함.\r\n");
      out.write("       \t\t\t$(\"#fileArea\").hide();\r\n");
      out.write("       \t    \t\r\n");
      out.write("       \t    \t// 이미지 영역 클릭 시 파일 첨부창 띄우기\r\n");
      out.write("       \t    \t$(\"#contentImgArea1\").click(function(){\r\n");
      out.write("       \t    \t\t$(\"#img1\").click();\r\n");
      out.write("       \t    \t});\r\n");
      out.write("       \t    \t$(\"#contentImgArea2\").click(function(){\r\n");
      out.write("       \t    \t\t$(\"#img2\").click();\r\n");
      out.write("       \t    \t});\r\n");
      out.write("       \t    \t$(\"#contentImgArea3\").click(function(){\r\n");
      out.write("       \t    \t\t$(\"#img3\").click();\r\n");
      out.write("       \t    \t});\r\n");
      out.write("       \t    \t$(\"#contentImgArea4\").click(function(){\r\n");
      out.write("       \t    \t\t$(\"#img4\").click();\r\n");
      out.write("       \t    \t});\r\n");
      out.write("        \t    \t\r\n");
      out.write("        \t});\r\n");
      out.write("        \t\r\n");
      out.write("   \t  \t\t// 각각의 영역에 파일을 첨부 했을 경우 미리 보기가 가능하도록 하는 함수\r\n");
      out.write("   \t\t    function LoadImg(value, num) {\r\n");
      out.write("   \t  \t\t\t\r\n");
      out.write("   \t\t    \tvar dot = $(value).val().lastIndexOf(\".\");\r\n");
      out.write("   \t\t    \tvar ext = $(value).val().substring(dot+1, $(value).val().length);\r\n");
      out.write("   \t\t    \t\r\n");
      out.write("   \t\t    \text = ext.toLowerCase();\r\n");
      out.write("   \t\t    \t\r\n");
      out.write("   \t\t    \tvar flag = true;\r\n");
      out.write("   \t\t    \tswitch(ext){ \r\n");
      out.write("   \t\t    \tcase \"jpg\" : case \"png\" : case \"gif\" : case \"jpeg\" : case \"bmp\" : case \"tiff\" : case \"raw\" :\r\n");
      out.write("   \t\t    \t\tflag = false; break;\r\n");
      out.write("   \t  \t\t\t}\r\n");
      out.write("   \t  \t\t\t\r\n");
      out.write("   \t\t    \t/* if(flag){\r\n");
      out.write("   \t\t    \t\talert(\"사진 파일만 업로드해주세요!\"); \r\n");
      out.write("   \t\t    \t} else{ */\r\n");
      out.write("   \t\t    \t\r\n");
      out.write("\t   \t\t    \t// 파일 업로드 시 업로드된 파일의 경로는 \r\n");
      out.write("\t   \t\t    \t// 해당 요소에 files라는 배열이 생성되며 저장된다.\r\n");
      out.write("\t   \t\t    \tif(value.files && value.files[0]){ //--> 파일이 선택이 된 경우\r\n");
      out.write("\t   \t\t    \t\tvar reader = new FileReader();\r\n");
      out.write("\t   \t\t    \t\treader.onload = function(e){\r\n");
      out.write("\t   \t\t    \t\t\tif(flag==false){\r\n");
      out.write("\t\t   \t\t    \t\t\tswitch(num){\r\n");
      out.write("\t\t   \t\t    \t\t\t\tcase 1 : $(\"#contentImg1\").prop(\"src\",e.target.result); break; \r\n");
      out.write("\t\t   \t\t    \t\t\t\tcase 2 : $(\"#contentImg2\").prop(\"src\",e.target.result); break;\r\n");
      out.write("\t\t   \t\t    \t\t\t\tcase 3 : $(\"#contentImg3\").prop(\"src\",e.target.result); break;\r\n");
      out.write("\t\t   \t\t    \t\t\t\tcase 4 : $(\"#contentImg4\").prop(\"src\",e.target.result); break;\r\n");
      out.write("\t\t   \t\t    \t\t\t}\r\n");
      out.write("\t   \t\t    \t\t\t}else{\r\n");
      out.write("\t\t   \t\t    \t\t\tswitch(num){\r\n");
      out.write("\t\t   \t\t    \t\t\t\tcase 1 : $(\"#contentImg1\").prop(\"src\",\"../images/document.png\");\r\n");
      out.write("\t\t   \t\t    \t\t\t\t         $(\".plese-upload1\").text(\"\"); break;\r\n");
      out.write("\t\t   \t\t    \t\t\t\tcase 2 : $(\"#contentImg2\").prop(\"src\",\"../images/document.png\");\r\n");
      out.write("\t\t   \t\t    \t\t\t\t         $(\".plese-upload2\").text(\"\"); break;\r\n");
      out.write("\t\t   \t\t    \t\t\t\tcase 3 : $(\"#contentImg3\").prop(\"src\",\"../images/document.png\");\r\n");
      out.write("\t\t   \t\t    \t\t\t\t         $(\".plese-upload3\").text(\"\"); break;\r\n");
      out.write("\t\t   \t\t    \t\t\t\tcase 4 : $(\"#contentImg4\").prop(\"src\",\"../images/document.png\");\r\n");
      out.write("\t\t   \t\t    \t\t\t\t         $(\".plese-upload4\").text(\"\"); break;\r\n");
      out.write("\t\t   \t\t    \t\t\t}\r\n");
      out.write("\t   \t\t    \t\t\t}\r\n");
      out.write("\t   \t\t    \t\t\t\t\r\n");
      out.write("\t   \t\t    \t\t}\r\n");
      out.write("\t   \t\t    \t\t\r\n");
      out.write("\t   \t\t    \t\t// file에서 내용(Content)을 읽어옴.\r\n");
      out.write("\t   \t\t    \t\t// + base64 인코딩된 경로를 반환\r\n");
      out.write("\t   \t\t    \t\treader.readAsDataURL(value.files[0]);\r\n");
      out.write("\t   \t\t    \t}\r\n");
      out.write("//    \t\t    }\r\n");
      out.write("   \t\t    }\r\n");
      out.write("        \t   \r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
