/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-03 10:26:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.studyNote;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.semi.member.model.vo.Member;
import com.semi.studynote.model.vo.StudyNote;
import com.semi.member.model.vo.Member;

public final class myStudyNoteManage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/studyNote/../common/footer.jsp", Long.valueOf(1580687082435L));
    _jspx_dependants.put("/WEB-INF/views/studyNote/../common/loginedHeader.jsp", Long.valueOf(1580720820389L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.semi.member.model.vo.Member");
    _jspx_imports_classes.add("com.semi.studynote.model.vo.StudyNote");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

List categorynm = (List)request.getAttribute("categorynm");
List<StudyNote> notelist = (List<StudyNote>)request.getAttribute("notelist");
List selectlike  = (List)request.getAttribute("selectlike");
List selectStudyNoteSetNM = (List)request.getAttribute("selectStudyNoteSetNM");



// 가져와야 되는 목록

// 1. 내 학습노트 /  2. 좋아요 숫자 / 3. 단어장 구성숫자
// 카테고리NM / title / count(*)단어장 / like


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("\tintegrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"../images/favicon.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"../images/icon57.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"../images/icon114.png\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css//common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/header.css\">\r\n");
      out.write("<title>온스터디</title>\r\n");
      out.write("<style>\r\n");
      out.write("/* 프로필 페이지 스타일 */\r\n");
      out.write("#container {\r\n");
      out.write("\tmargin: 200px 0 100px 0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#profile-wrap .member-profile {\r\n");
      out.write("\twidth: 25%;\r\n");
      out.write("\tmin-width: 120px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#profile-wrap .profile-sub-list-wrap {\r\n");
      out.write("\tmargin-left: 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#profile-wrap .member-profile-info {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("\tmargin-top: 2%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#profile-wrap .member-profile-info dt {\r\n");
      out.write("\tfont-size: 3em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#profile-wrap .member-profile-info dd {\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#profile-wrap .follow-btn {\r\n");
      out.write("\tbackground-color: #f15a25;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\twidth: 11%;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tmin-width: 80px;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\tborder-radius: 30px;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("\ttransform: translateY(-35px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#study-note-list .study-note-list-title {\r\n");
      out.write("\ttext-align: initial;\r\n");
      out.write("\tmargin: 50px 0;\r\n");
      out.write("\tfont-size: 35px;\r\n");
      out.write("\tborder-bottom: 4px solid #212529;\r\n");
      out.write("\tpadding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#study-note-list ul li {\r\n");
      out.write("\tbackground-color: #9e9e9e;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tcolor: #333333;\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\ttransition: all 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#study-note-list ul li:hover {\r\n");
      out.write("\tbackground-color: #f15a25;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* #study-note-list ul li:hover{\r\n");
      out.write("  background-color: #f15a25;\r\n");
      out.write("}\r\n");
      out.write("#study-note-list ul li:hover{\r\n");
      out.write("  background-color: #f15a25;\r\n");
      out.write("} */\r\n");
      out.write("#study-note-list ul li>p {\r\n");
      out.write("\tmargin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#study-note-list .category-name, #study-note-list .study-note-name {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tfont-size: 1.5em;\r\n");
      out.write("\tline-height: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#study-note-list .etc-info {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#study-note-list .etc-info .content-amount {\r\n");
      out.write("\tline-height: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#study-note-list .etc-info .like-btn {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tbottom: 10px;\r\n");
      out.write("\tright: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#study-note-list .etc-info .like-btn>.like-btn-img {\r\n");
      out.write("\twidth: 25px;\r\n");
      out.write("\theight: 25px;\r\n");
      out.write("\tbackground-image: url(../images/like-btn-off2.png);\r\n");
      out.write("\tbackground-size: 25px 25px;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-position: 50% 0%;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#study-note-list .etc-info .like-btn>.like-btn-img.on {\r\n");
      out.write("\tbackground-image: url(../images/like-btn-on2.png);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#study-note-list .etc-info .like-btn>span.like-count {\r\n");
      out.write("\ttransform: translateY(-4px);\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 767px) {\r\n");
      out.write("\t/*767px : 구조가 바뀌는 기준*/\r\n");
      out.write("\t#study-note-list .category-name, #study-note-list .study-note-name,\r\n");
      out.write("\t\t#study-note-list .etc-info .content-amount {\r\n");
      out.write("\t\tline-height: 40px;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 991px) {\r\n");
      out.write("\t#profile-wrap .follow-btn {\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-w1 {\r\n");
      out.write("\tbackground-color: #f15a25;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fl-lt {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member) session.getAttribute("loginMember");
	if(loginMember == null){
		System.out.println("세션 만료 실행");
		session.setAttribute("msg", "세션이 만료되어 메인페이지로 돌아갑니다.");
		response.sendRedirect(request.getContextPath());
	}
	
	int[] follow = (int[])session.getAttribute("follow");
	String memberImagePath = (String)session.getAttribute("memberImagePath");
	String profileImagePath = "/images/navi-icon-default.png"; // default 이미지 경로
	String msg = (String)session.getAttribute("msg");
	
	// null이 아니면 받아온 이미지 경로로 변경
	if(memberImagePath != null) profileImagePath = memberImagePath;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("\tintegrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/favicon.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/icon57.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/icon114.png\">\r\n");
      out.write("<script>\r\n");
      out.write("\t");
 if(msg != null) {
      out.write("\r\n");
      out.write("\t\talert(\"");
      out.print( msg );
      out.write("\");\r\n");
      out.write("\t\t");
 session.removeAttribute("msg"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
 } 
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/common.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap icon link -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/76b49c6d9b.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\" class='m-0'>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"d-flex flex-column flex-md-row align-items-center mb-3 mt-3\"\r\n");
      out.write("\t\t\t\t\tid=\"header-wrap\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"mypage-btn\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../images/mypage-icon.png\" alt=\"마이페이지 버튼\"></a>\r\n");
      out.write("\t\t\t\t\t<h1 class=\"my-0 mr-md-auto font-weight-normal text-white\"\r\n");
      out.write("\t\t\t\t\t\tid=\"logo-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/main\"> <img class=\"logo-img\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"../images/logo2-white.png\" alt=\"로고\" id=\"logo-img\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t<nav class=\"my-2 my-md-0\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/StudyNoteController/list\" class=\"menu-list\" class=\"menu-list\">학습노트</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/StudyNoteController/list\" class=\"sub-menu-list\">학습노트 검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/StudyNoteController/make\" class=\"sub-menu-list\">학습노트 만들기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/onstudy/main\" class=\"menu-list\">온스터디</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/onstudy/main\" class=\"sub-menu-list\">온스터디 검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/onstudy/createView\" class=\"sub-menu-list\">온스터디 만들기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/onstudy/certify\" class=\"sub-menu-list\">온스터디 인증하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/onstudy/manage\" class=\"sub-menu-list\">온스터디 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/board/freeBoardList?boardType=F\" class=\"menu-list\">게시판</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/board/freeBoardList?boardType=F\" class=\"sub-menu-list\">자유 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/board/declareBoardList?boardType=SD\" class=\"sub-menu-list\">건의/신고 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//헤더 메뉴 호버 이벤트\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\".menu>li\").on({\r\n");
      out.write("\t\t\t\tmouseenter : function() {\r\n");
      out.write("\t\t\t\t\t$(this).find(\"ul\").stop().slideDown(300);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tmouseleave : function() {\r\n");
      out.write("\t\t\t\t\t$(this).find(\"ul\").stop().slideUp(300);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div id=\"mypage-nav\">\r\n");
      out.write("\t\t<div class=\"info-area\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath() + profileImagePath );
      out.write("\" alt=\"회원아이콘\"\r\n");
      out.write("\t\t\t\tclass=\"profile-icon\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>");
      out.print(loginMember.getMemberId() );
      out.write(" 님</li>\r\n");
      out.write("\t\t\t\t<li>");
      out.print(loginMember.getMemberPoint() );
      out.write(" 포인트</li>\r\n");
      out.write("\t\t\t\t<li>팔로워 수 : <span id=\"mypage-follower\">");
      out.print(follow[1] );
      out.write("</span>명</li>\r\n");
      out.write("\t\t\t\t<li>팔로잉 수 : <span id=\"mypage-following\">");
      out.print(follow[0] );
      out.write("</span>명</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/mypage\"\tclass=\"bell-setting-btn\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/setting-off.png\" alt=\"세팅버튼\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"mypage-btn-list\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/StudyNoteController/selectStudyNoteSet\">학습노트 관리</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/onstudyList\">온스터디 내역</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/logout\">로그아웃</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"shadow\"></div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//좌측 마이페이지 버튼 클릭시 이벤트\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\".mypage-btn>img\").on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\t$(\"#mypage-nav\").fadeIn(300);\r\n");
      out.write("\t\t\t\t\t$(\"#shadow\").show(0);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#shadow\").on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\t$(this).hide(0);\r\n");
      out.write("\t\t\t\t\t$(\"#mypage-nav\").fadeOut(300);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 미니버튼 호버시 색상변경 이벤트\r\n");
      out.write("\t\t\t$(\".bell-setting-btn\").on(\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tmouseenter : function() {\r\n");
      out.write("\t\t\t\t\t\t\tvar renameImg = $(this).find(\"img\").prop(\"src\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.replace(\"-off.\", \"-on.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(this).find(\"img\").prop(\"src\", renameImg);\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tmouseleave : function() {\r\n");
      out.write("\t\t\t\t\t\t\tvar renameImg = $(this).find(\"img\").prop(\"src\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.replace(\"-on.\", \"-off.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(this).find(\"img\").prop(\"src\", renameImg);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"button-top\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"top-btn\">TOP</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction scrollFunction() {\r\n");
      out.write("\t\t\tif ($(window).scrollTop() >= 200) {\r\n");
      out.write("\t\t\t\t$('#button-top').show(0);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#button-top').hide(0);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tscrollFunction();\r\n");
      out.write("\t\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t\t\tscrollFunction();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('#button-top').on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\t$('html,body').stop().animate({\r\n");
      out.write("\t\t\t\t\t\tscrollTop : 0\r\n");
      out.write("\t\t\t\t\t}, 600);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- content 시작 -->\r\n");
      out.write("\t<div id=\"container\"\r\n");
      out.write("\t\tstyle=\"margin: 200px auto; text-align: center; color: #333333;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"study-note-list\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p class=\"study-note-list-title \">\r\n");
      out.write("\t\t\t\t\t\t\t학습노트\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick = \"location.href='");
      out.print( request.getContextPath());
      out.write("/StudyNoteController/make'\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"col-2 form-control orange-hover-btn\" type=\"submit\" style=\"width: 30%; margin-left: 83%; font-size: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t새 학습노트 만들기</button>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var me = \"");
      out.print(loginMember.getMemberId());
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).on(\"change\",\"#display-selector\",function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar selector = $(\"#display-selector\").val();\r\n");
      out.write("\t\r\n");
      out.write("\tif(selector==\"all\"){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$(\".mine\").attr('style', \"display:block;\");\t\r\n");
      out.write("\t\t\t$('.other').attr('style', \"display:block;\");\r\n");
      out.write("\t}\r\n");
      out.write("\tif(selector==\"other\"){\r\n");
      out.write("\t\t\t$('.mine').attr('style', \"display:none;\");\r\n");
      out.write("\t\t\t$('.other').attr('style', \"display:block;\");\r\n");
      out.write("\t}\r\n");
      out.write("\tif(selector==\"mine\"){\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  $('.mine').attr('style', \"display:block;\");\r\n");
      out.write("\t\t  $('.other').attr('style', \"display:none;\");\r\n");
      out.write("\t}  \r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"display-selector\" style=\"margin-left: 85%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"all\">노트 전체</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"mine\">내가 쓴 노트</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"other\">가져오기 한 노트</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
if(notelist!=null)  {
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
for(int i = 0; i<notelist.size();i++) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"");
if(notelist.get(i).getmemberId().equals(loginMember.getMemberId())){
      out.write("mine");
}else{
      out.write("other");
} 
      out.write("\" id=\"");
      out.print(notelist.get(i).getStudyNoteNo() );
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t >\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"col-md-3 category-name moving-to-detail\">");
      out.print(notelist.get(i).getcategoryNM() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"col-md-7 study-note-name moving-to-detail\">");
      out.print(notelist.get(i).getStudyNoteTitle() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"col-md-2 etc-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\" id=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"margin-top: 10px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn-w1 update-btn\" style=\"width: 40%;\">수정</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"delete-btn btn-w1\" style=\"width: 40%;\">삭제</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"update-btn-flag\"  style=\"display:none;\">");
      out.print(notelist.get(i).getmemberId());
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t<br> \r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"content-amount\">");
      out.print(selectStudyNoteSetNM.get(i));
      out.write("</span>세트\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;<span class=\"like-btn\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<span ><img src=\"../images/like-btn-off2.png\" alt=\"추천이미지\"  style=\"font-size :15px; width : 25px ;height : 25px; \" ></span> \r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"like-count\">");
      out.print(selectlike.get(i));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
}
              } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("    // 팔로우 버튼 클릭시 이벤트\r\n");
      out.write("    $(function () {\r\n");
      out.write("      var followToggle = 0;\r\n");
      out.write("      $(\".follow-btn\").on({\r\n");
      out.write("        click: function () {\r\n");
      out.write("          if (followToggle == 0) {\r\n");
      out.write("            var count = $(\".follower-count dt\").html();\r\n");
      out.write("            count++;\r\n");
      out.write("            $(\".follower-count dt\").html(count);\r\n");
      out.write("            followToggle = 1;\r\n");
      out.write("            $(\".follow-btn\").html(\"팔로우 취소\");\r\n");
      out.write("          } \r\n");
      out.write("          \r\n");
      out.write("          else {\r\n");
      out.write("            var count = $(\".follower-count dt\").html();\r\n");
      out.write("            count--;\r\n");
      out.write("            $(\".follower-count dt\").html(count);\r\n");
      out.write("            followToggle = 0;\r\n");
      out.write("            $(\".follow-btn\").html(\"팔로우\");\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      // 좋아요 버튼 클릭시 이벤트\r\n");
      out.write("      $(\".like-btn-img\").on({\r\n");
      out.write("        click: function () {\r\n");
      out.write("          $(this).toggleClass(\"on\");\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      $(\".btn-w1\").mouseenter(function () {\r\n");
      out.write("        $(this).css(\"backgroundColor\", \"white\").css(\"color\", \"#f15a25\")\r\n");
      out.write("      });\r\n");
      out.write("      $(\".btn-w1\").mouseleave(function () {\r\n");
      out.write("        $(this).css(\"backgroundColor\", \"#f15a25\").css(\"color\", \"black\")\r\n");
      out.write("      });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $(\".update-btn\").click(function(){\r\n");
      out.write("    \tvar noteNumber = $(this).parent().parent().prop(\"id\");\r\n");
      out.write("    \tvar result = confirm(\"수정하시겠습니까?\");\r\n");
      out.write("    \t\r\n");
      out.write("    \tvar insertFlag = $(this).siblings(\".update-btn-flag\").text();\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 수정 관련 \r\n");
      out.write("    \tif(result){\r\n");
      out.write("    \t\tif(insertFlag==me){\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\tlocation.href =\"");
      out.print(request.getContextPath());
      out.write("/StudyNoteController/loadingStudyNote?noteNumber=\"+noteNumber;\r\n");
      out.write("    \t\t}else{\r\n");
      out.write("    \t\t\talert(\"다른 사람의노트는 수정할 수 없습니다.\");\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(function(){\r\n");
      out.write("    \r\n");
      out.write("    \t\r\n");
      out.write("    \t$(\".moving-to-detail\").on(\"click\",function(){\r\n");
      out.write("    \tvar noteNumber = $(this).parent().prop(\"id\");\r\n");
      out.write("    \t// console.log($(this).siblings(\".content-amount\").text())\r\n");
      out.write("    \tvar moveDetailDistinct = $(this).siblings(\".content-amount\").text()\r\n");
      out.write("    \tconsole.log(\"로그 2\"+moveDetailDistinct);\r\n");
      out.write("    \t\r\n");
      out.write("    \tif(moveDetailDistinct>0){\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/StudyNoteController/movetodetail?noteNumber=\"+noteNumber;\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\talert(\"구성요소가 0개인 학습노트는 들어갈 수 없습니다.\");\r\n");
      out.write("    \t\treturn false;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t})\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(function(){\r\n");
      out.write("    \t\r\n");
      out.write("    \t$(document).on(\"click\", \".delete-btn\", function() {\r\n");
      out.write("            \r\n");
      out.write("\t   \r\n");
      out.write("\t    \t  var result1 = confirm(\"삭제하시겠습니까?\");\r\n");
      out.write("\t  \t      var index = $(this).parent().parent().prop(\"id\");\r\n");
      out.write("\t  \t      var deleteThis = $(this).parent().parent()\r\n");
      out.write("\t  \t      if (result1) {\r\n");
      out.write("\t  \t    \t  $.ajax({\r\n");
      out.write("\t  \t    \t\turl : \"");
      out.print( request.getContextPath());
      out.write("/StudyNoteController/delete\",\r\n");
      out.write("\t  \t    \t\tdata : {index : index},\r\n");
      out.write("\t  \t    \t\ttype : \"post\",\r\n");
      out.write("\t  \t    \t\tasync : \"false\",\r\n");
      out.write("\t  \t    \t\tsuccess : function(result){\r\n");
      out.write("\t  \t    \t\t\t\tconsole.log(result)\r\n");
      out.write("\t  \t    \t\t\tif(result>0){\r\n");
      out.write("\t  \t    \t\t\t\tdeleteThis.remove();\r\n");
      out.write("\t  \t    \t\t\t}\r\n");
      out.write("\t  \t        \t\t\r\n");
      out.write("\t  \t    \t\t}\r\n");
      out.write("\t  \t    \t  \r\n");
      out.write("\t  \t    \t  \r\n");
      out.write("\t  \t    \t  });\r\n");
      out.write("\t  \t    \t\r\n");
      out.write("\t  \t      }\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    });\r\n");
      out.write("    });\r\n");
      out.write("\t    \r\n");
      out.write("\r\n");
      out.write("  </script>\r\n");
      out.write("\t<!-- content 종료 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- footer 시작 -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("        <div class=\"container-fluid container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4 footer-logo-wrap\">\r\n");
      out.write("                            <img class=\"footer-logo\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/logo2-white.png\" alt=\"푸터로고\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-8\">\r\n");
      out.write("                            <p class=\"copyright\">&copy; 2020 NOKJO COMPANY. ALL RIGHTS RESERVED.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
