/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-04 02:12:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.cardTest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.semi.cardTest.model.vo.StudyCard;
import com.semi.cardTest.model.vo.ProgressBar;

public final class examPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.semi.cardTest.model.vo.ProgressBar");
    _jspx_imports_classes.add("com.semi.cardTest.model.vo.StudyCard");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	String msg = (String)session.getAttribute("msg");
	System.out.println(msg);

	StudyCard sCard = (StudyCard) session.getAttribute("sCard");
	ProgressBar pBar = (ProgressBar) session.getAttribute("proBar");
	System.out.println("view 단 sCard : " + sCard);
	System.out.println("view 단 pBar : " + pBar);
	
	int SNnum = (int)request.getAttribute("SNnum");

	int wholeQ = pBar.getWholeQuestion();
	int solvedQ = pBar.getSolvedQuestion();
	int correctQ = pBar.getCorrectAnswer();
	int wrongQ = pBar.getWrongAnswer();

	int wholeP = 0;
	if ( wholeQ==0 ){
		wholeP = 0;
	} else {
		wholeP = (int)((double)pBar.getSolvedQuestion()/pBar.getWholeQuestion()*100);
	}
	
	
	int correctP = 0;
	if ( solvedQ==0 ){
		correctP = 0;
	} else {
		correctP = (int)((double)pBar.getCorrectAnswer()/pBar.getSolvedQuestion()*100);
	}
	
	int wrongP = 0;
	if ( solvedQ==0 ){
		wrongP = 0;
	} else {
	    wrongP = (int)((double)pBar.getWrongAnswer()/pBar.getSolvedQuestion()*100);
	}
	

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\n");
      out.write("\tintegrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\"\n");
      out.write("\tcrossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\n");
      out.write("\tintegrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/favicon.png\">\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"images/icon57.png\">\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"images/icon114.png\">\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/header2.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/common.css\">\n");
      out.write("<title>학습노트 시험보기</title>\n");
      out.write("<style>\n");
      out.write("/* .outer {\n");
      out.write("            position: relative;\n");
      out.write("        } */\n");
      out.write(".study-gage {\n");
      out.write("\tfloat: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".study-gage2 {\n");
      out.write("\tfloat: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn-answer {\n");
      out.write("\tbackground-color: #f15a25;\n");
      out.write("\tcolor: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn-answer:hover {\n");
      out.write("\tbackground-color: white;\n");
      out.write("\tcolor: #f15a25;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#backBtn {\n");
      out.write("\tfont-size: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#msgArea{\n");
      out.write("\tmargin-top : 50px;\n");
      out.write("\twidth: 65%\n");
      out.write("}\n");
      out.write("\n");
      out.write("h5.card-mean{\n");
      out.write(" line-height:28px;\n");
      out.write("}  \n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\t\n");
      out.write("<script>\n");
 if(msg != null) {
      out.write("  \n");
      out.write("alert(\"");
      out.print(msg );
      out.write("\");\n");
 	
session.removeAttribute("msg");
}

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- 헤더 시작 -->\n");
      out.write("\n");
      out.write("\t<!-- content 시작 -->\n");
      out.write("\t<div id=\"container\" style=\"margin: 240px auto; text-align: center; font-size: 50px; color: #333333;\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("\n");
      out.write("                <div class=\"col-2\" >\n");
      out.write("                   \n");
      out.write("\n");
      out.write("                    <!-- 진행률 시작 -->\n");
      out.write("\n");
      out.write("                    <!-- 진행률 종료 3 -->\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                \n");
      out.write("                    <div class=\"col-10\" >\n");
      out.write("                        \n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-2\" style=\"border-right: double;\">\n");
      out.write("                                <div class=\"col-12 row\" style=\"margin: 0, auto; font-size: 20px; font-weight:bolder;\">\n");
      out.write("                             \t       주관식</div>\n");
      out.write("                                <a href=\"");
      out.print( request.getContextPath());
      out.write("/StudyNoteController/movetodetail?noteNumber=");
      out.print(SNnum);
      out.write("\" id=\"backBtn\"\n");
      out.write("                                    style=\"text-align: right; font-weight:bolder; font-size: 30%;\">&lt;&lt;뒤로가기</a> <br>\n");
      out.write("\n");
      out.write("                                <div class=\"progress\">\n");
      out.write("                                    <div class=\"progress-bar\" style=\"width:");
      out.print(wholeP);
      out.write("%\"></div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-6\">\n");
      out.write("                                        <p style=\"font-size: 30%;\">진행률</p>\n");
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-6\">\n");
      out.write("                                        <div class=\"row\">\n");
      out.write("\n");
      out.write("                                            <p style=\"font-size: 30%; text-align: right;\">&nbsp;");
      out.print(solvedQ);
      out.write("</p>\n");
      out.write("                                            <p style=\"font-size: 30%; text-align: right;\">/</p>\n");
      out.write("                                            <p style=\"font-size: 30%; text-align: right;\">");
      out.print(wholeQ);
      out.write("</p>\n");
      out.write("\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"progress\">\n");
      out.write("                                    <div class=\"progress-bar\" style=\"width:");
      out.print(correctP);
      out.write("%\"></div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-6\">\n");
      out.write("                                        <p style=\"font-size: 30%;\">정답률</p>\n");
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-6\">\n");
      out.write("                                        <div class=\"row\">\n");
      out.write("\n");
      out.write("                                            <p style=\"font-size: 30%; text-align: right;\">&nbsp;");
      out.print(correctQ);
      out.write("</p>\n");
      out.write("                                            <p style=\"font-size: 30%; text-align: right;\">/</p>\n");
      out.write("                                            <p style=\"font-size: 30%; text-align: right;\">");
      out.print(solvedQ);
      out.write("</p>\n");
      out.write("\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"progress\">\n");
      out.write("                                    <div class=\"progress-bar\" style=\"width:");
      out.print(wrongP);
      out.write("%\"></div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-6\">\n");
      out.write("                                        <p style=\"font-size: 30%;\">오답률</p>\n");
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-6\">\n");
      out.write("                                        <div class=\"row\">\n");
      out.write("\n");
      out.write("                                            <p style=\"font-size: 30%; text-align: right;\">&nbsp;");
      out.print(wrongQ);
      out.write("</p>\n");
      out.write("                                            <p style=\"font-size: 30%; text-align: right;\">/</p>\n");
      out.write("                                            <p style=\"font-size: 30%; text-align: right;\">");
      out.print(solvedQ);
      out.write("</p>\n");
      out.write("\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                               \n");
      out.write("                            </div>\n");
      out.write("                           \n");
      out.write("                            <!-- 정답 입력 -->\n");
      out.write("                        <form id=\"AnswerForm\" action=\"checkAnswer\" method=\"POST\" role=\"form\" style=\"width:700px;\">    \n");
      out.write("                        <div class=\"col-9\" style=\"margin-left: 20px;\">\n");
      out.write("\n");
      out.write("                               <input type=\"hidden\" name=\"SNnum\" value=\"");
      out.print(SNnum );
      out.write("\">\n");
      out.write("                                    <div class=\"row\" style=\"height: 300px;\" >\n");
      out.write("                                        <div class=\"text-area\" style=\"text-align:left; line-height:10px;\">\n");
      out.write("                                            <h5 class=\"card-mean\">");
      out.print(sCard.getCardSetMean());
      out.write("</h5>\n");
      out.write("                                        </div>    \n");
      out.write("                                    </div> \n");
      out.write("                                 <div class=\"row\" style=\"font-size: 20px;\" id=\"answerArea\">       \n");
      out.write("                                    <input type=\"text\" placeholder=\"정답입력\" id=\"answer\" name=\"answer\" style=\"width: 70%; \" class=\"form-control input-content input-comment\">\n");
      out.write("                                    &nbsp; &nbsp;\n");
      out.write("                                    <button type=\"submit\" class=\"btn form-control orange-btn-style orange-hover-btn\" id=\"submitBtn\"\n");
      out.write("                                        style=\"width: 25%\">정답</button>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"row\" id=\"msgArea\">\n");
      out.write("                                    <div id=\"checkAnswer\" style=\" font-size: 30px; font-weight:bolder;\"> \n");
      out.write("                                     </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <br>\n");
      out.write("                                <div class=\"row\" style=\"text-align: right; margin-left: 80%;\">\n");
      out.write("                                    <button type=\"button\"\n");
      out.write("                                        style=\"background-color: white; border: none; box-shadow: none; font-weight:bolder; font-size: 30%;\"\n");
      out.write("                                        onclick='location.href=\"");
      out.print(request.getContextPath() );
      out.write("/cardTest/test?SNnum=");
      out.print(SNnum);
      out.write("\"'>\n");
      out.write("                                                                                          건너뛰기>></button>\n");
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            </form>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("               \n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\t<!-- content 종료 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- footer 시작 -->\n");
      out.write("\t<div id=\"footer\">\n");
      out.write("\t\t<div class=\"container-fluid container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4 footer-logo-wrap\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"footer-logo\" src=\"../images/logo2-white.png\" alt=\"푸터로고\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-8\">\n");
      out.write("\t\t\t\t\t\t\t<p class=\"copyright\">&copy; 2020 NOKJO COMPANY. ALL RIGHTS\n");
      out.write("\t\t\t\t\t\t\t\tRESERVED.</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- footer 종료 -->\n");
      out.write("\n");
      out.write("\t<div id=\"button-top\">\n");
      out.write("\t\t<button type=\"button\" class=\"top-btn\">TOP</button>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<script>\n");
      out.write("\t\tfunction scrollFunction() {\n");
      out.write("\t\t\tif ($(window).scrollTop() >= 200) {\n");
      out.write("\t\t\t\t$('#button-top').show(0);\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\t$('#button-top').hide(0);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\t$(function() {\n");
      out.write("\t\t\tscrollFunction();\n");
      out.write("\t\t\t$(window).scroll(function() {\n");
      out.write("\t\t\t\tscrollFunction();\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t$('#button-top').on({\n");
      out.write("\t\t\t\tclick : function() {\n");
      out.write("\t\t\t\t\t$('html,body').stop().animate({\n");
      out.write("\t\t\t\t\t\tscrollTop : 0\n");
      out.write("\t\t\t\t\t}, 600);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\n");
      out.write("\t\tintegrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\n");
      out.write("\t\tintegrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
