/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-01 04:00:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.onstudy.member.model.vo.PageInfo;
import java.util.List;
import com.onstudy.member.model.vo.Member;
import com.onstudy.member.model.vo.Member;

public final class memberList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/admin/sideBar.jsp", Long.valueOf(1580518640461L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.onstudy.member.model.vo.PageInfo");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.onstudy.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	PageInfo pInf = (PageInfo)request.getAttribute("pInf");
	List<Member> mList = (List<Member>)request.getAttribute("mList");
	String condition = request.getParameter("condition");
	String content = request.getParameter("content");
	
	int listCount = pInf.getListCount();
	int currentPage = pInf.getCurrentPage();
	int maxPage = pInf.getMaxPage();
	int startPage = pInf.getStartPage();
	int endPage = pInf.getEndPage();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	Member admin = (Member) session.getAttribute("loginMember");
	if(admin == null){
		response.sendRedirect(request.getContextPath());
	}
	String msg = (String)session.getAttribute("msg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script>\r\n");
      out.write("\t");
 if(msg != null) {
      out.write("\r\n");
      out.write("\t\talert(\"");
      out.print( msg );
      out.write("\");\r\n");
      out.write("\t\t");
 session.removeAttribute("msg"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
 } 
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("\tintegrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"img/favicon.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"img/icon57.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"img/icon114.png\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/adminPage-sideBar.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://code.jquery.com/jquery-3.3.1.js\"></script>\r\n");
      out.write("<title>온 스터디</title>\r\n");
      out.write("<style>\r\n");
      out.write("\ta{\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 관리자 페이지 사이드바 메뉴 -->\r\n");
      out.write("\t<div class=\"sidenav\">\r\n");
      out.write("\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/logo1-white.png\" id=\"adminTitleImg\">\r\n");
      out.write("\t\t<p id=\"adminSidebarTitle\">Admin</p>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/memberList\">회원 목록 조회</a>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/onstudyList\">온스터디 목록 조회</a>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<p id=\"adminBoardTitle\">게시판</p>\r\n");
      out.write("\t\t<a href=\"boardList?boardType=F\">-자유게시판</a>\r\n");
      out.write("\t\t<a href=\"boardList?boardType=S\">-건의게시판</a>\r\n");
      out.write("\t\t<a href=\"boardList?boardType=D\">-신고게시판</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 관리자 페이지 사이드바 메뉴 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath() );
      out.write("/css/adminPage-list.css\">\r\n");
      out.write("<title>온스터디</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"content-title\">회원 목록 조회</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"board-content\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberList\"\r\n");
      out.write("\t\t\t\t\t\t\t method=\"get\" class=\"board-form\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 카테고리, 검색input, 버튼 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"search-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn form-control orange-hover-btn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"searchBtn\" type=\"submit\">검색</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control input-comment\" name=\"content\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"검색어를 입력해 주세요\" id=\"searchBox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select\tclass=\"form-control\" id=\"selectOption\" name=\"condition\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"회원번호\">회원번호</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"아이디\">아이디</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"이름\">이름</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"전화번호\">전화번호</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"포인트\">포인트</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"신고회수\">신고회수</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"정지여부\">정지여부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 카테고리, 검색input, 버튼 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 테이블 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table class=\"table table-bordered table-striped\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"simulate_log\" style=\"padding: 0px 0px\" width=\"100%\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" data-sortable=\"true\">회원번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">아이디</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">이름</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">전화번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">포인트</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">신고회수</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">정지여부</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 if(mList.isEmpty()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"7\">존재하는 게시글이 없습니다.</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 for(Member member : mList){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr class=\"tableContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( member.getMemberNo() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( member.getMemberId() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( member.getMemberNm() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( member.getMemberPhone() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( member.getMemberPoint() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( member.getMemberDeclarCount() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( member.getMemberStatus() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 } } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 테이블 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 페이징바 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"clear: both;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(currentPage > 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 맨 처음으로(<<) -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"page-link page-first\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberList?currentPage=1&condition=");
      out.print(condition);
      out.write("&content=");
      out.print(content);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&lt;&lt;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 이전으로(<) -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"page-link page-pre\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberList?currentPage=");
      out.print( currentPage-1 );
      out.write("&condition=");
      out.print(condition);
      out.write("&content=");
      out.print(content);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&lt;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 10개의 페이지 목록 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 for(int p = startPage; p <= endPage; p++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(p == currentPage) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link page-now\">");
      out.print( p );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"page-link page-other\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberList?currentPage=");
      out.print( p );
      out.write("&condition=");
      out.print(condition);
      out.write("&content=");
      out.print(content);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print( p );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 다음 페이지로(>) -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(currentPage < maxPage){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link page-next\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberList?currentPage=");
      out.print( currentPage+1 );
      out.write("&condition=");
      out.print(condition);
      out.write("&content=");
      out.print(content);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&gt;</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 맨 끝으로(>>) -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link page-end\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberList?currentPage=");
      out.print( maxPage );
      out.write("&condition=");
      out.print(condition);
      out.write("&content=");
      out.print(content);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&gt;&gt;</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 테이블 sorting  ( datatable 기능 ) -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\tvar condition = \"");
      out.print( condition );
      out.write("\";\r\n");
      out.write("\t\t\tvar content = \"");
      out.print( content );
      out.write("\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(content != \"null\" && condition != \"null\"){\r\n");
      out.write("\t\t\t\t$.each($(\"select[name=condition] > option\"), function(index, item){\r\n");
      out.write("\t\t\t\t\tif($(item).val() == condition){\r\n");
      out.write("\t\t\t\t\t\t$(item).prop(\"selected\",\"true\");\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"input[name=content]\").val(content);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#simulate_log td\").click(function(){\r\n");
      out.write("\t\t\t\tvar memberNo = $(this).parent().children().eq(0).text();\r\n");
      out.write("\t\t\t\t// 쿼리스트링을 이용하여 get 방식으로 글 번호를 server로 전달\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberDetail?memberNo=\" + memberNo;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}).mouseenter(function(){\r\n");
      out.write("\t\t\t\t$(this).parent().css(\"cursor\", \"pointer\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
