/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-03 06:39:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.onstudy;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.semi.onstudy.model.vo.Onstudy;
import com.semi.onstudy.model.vo.PageInfo;
import com.semi.member.model.vo.Member;

public final class onstudySearchList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/onstudy/../common/footer.jsp", Long.valueOf(1580687082435L));
    _jspx_dependants.put("/WEB-INF/views/onstudy/../common/loginedHeader.jsp", Long.valueOf(1580698249394L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.semi.onstudy.model.vo.Onstudy");
    _jspx_imports_classes.add("com.semi.member.model.vo.Member");
    _jspx_imports_classes.add("com.semi.onstudy.model.vo.PageInfo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

//String msg = (String)session.getAttribute("msg");
List<Onstudy> sList = (List<Onstudy>)request.getAttribute("sList");
PageInfo pInf = (PageInfo)request.getAttribute("pInf");
String condition=(String)session.getAttribute("condition");


String searchKeyword = request.getParameter("search-keyword");
String searchCategory = request.getParameter("search-category");
String searchStart = request.getParameter("search-start");
String searchEnd = request.getParameter("search-end");

int listCount = pInf.getListCount();
int currentPage = pInf.getCurrentPage();
int maxPage = pInf.getMaxPage();
int startPage = pInf.getStartPage();
int endPage = pInf.getEndPage();

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("    <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("\t    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\" integrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\" crossorigin=\"anonymous\">\r\n");
      out.write("\t    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\" integrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t    <link rel=\"shortcut icon\" href=\"img/favicon.png\">\r\n");
      out.write("\t    <link rel=\"apple-touch-icon-precomposed\" href=\"img/icon57.png\">\r\n");
      out.write("\t    <link rel=\"apple-touch-icon-precomposed\" href=\"img/icon114.png\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"../css/common.css\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"../css/header.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../css/onstudyMain.css\">\r\n");
      out.write("\t\t   \r\n");
      out.write("\t    <title>온스터디</title>\r\n");
      out.write("\t    <style>\r\n");
      out.write("\t      #container{\r\n");
      out.write("\t        margin: 200px 0 100px 0;\r\n");
      out.write("\t      }\r\n");
      out.write("\t    </style>\r\n");
      out.write("\t\r\n");
      out.write("\t    </head>\r\n");
      out.write("\t    <body>\r\n");
      out.write("\t     ");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member) session.getAttribute("loginMember");
	if(loginMember == null){
		System.out.println("세션 만료 실행");
		session.setAttribute("msg", "세션이 만료되어 메인페이지로 돌아갑니다.");
		response.sendRedirect(request.getContextPath());
	}
	
	int[] follow = (int[])session.getAttribute("follow");
	String memberImagePath = (String)session.getAttribute("memberImagePath");
	String profileImagePath = "/images/navi-icon-default.png"; // default 이미지 경로
	String msg = (String)session.getAttribute("msg");
	
	// null이 아니면 받아온 이미지 경로로 변경
	if(memberImagePath != null) profileImagePath = memberImagePath;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("\tintegrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/favicon.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/icon57.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/icon114.png\">\r\n");
      out.write("<script>\r\n");
      out.write("\t");
 if(msg != null) {
      out.write("\r\n");
      out.write("\t\talert(\"");
      out.print( msg );
      out.write("\");\r\n");
      out.write("\t\t");
 session.removeAttribute("msg"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
 } 
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/common.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap icon link -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/76b49c6d9b.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\" class='m-0'>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"d-flex flex-column flex-md-row align-items-center mb-3 mt-3\"\r\n");
      out.write("\t\t\t\t\tid=\"header-wrap\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"mypage-btn\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../images/mypage-icon.png\" alt=\"마이페이지 버튼\"></a>\r\n");
      out.write("\t\t\t\t\t<h1 class=\"my-0 mr-md-auto font-weight-normal text-white\"\r\n");
      out.write("\t\t\t\t\t\tid=\"logo-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/main\"> <img class=\"logo-img\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"../images/logo2-white.png\" alt=\"로고\" id=\"logo-img\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t<nav class=\"my-2 my-md-0\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"menu-list\">학습노트</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"sub-menu-list\">학습노트 검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"sub-menu-list\">학습노트 만들기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/onstudy/main\" class=\"menu-list\">온스터디</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/onstudy/main\" class=\"sub-menu-list\">온스터디 검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/onstudy/createView\" class=\"sub-menu-list\">온스터디 만들기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/onstudy/certify\" class=\"sub-menu-list\">온스터디 인증하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/onstudy/manage\" class=\"sub-menu-list\">온스터디 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/board/freeBoardList?boardType=F\" class=\"menu-list\">게시판</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/board/freeBoardList?boardType=F\" class=\"sub-menu-list\">자유 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/board/declareBoardList?boardType=SD\" class=\"sub-menu-list\">건의/신고 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//헤더 메뉴 호버 이벤트\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\".menu>li\").on({\r\n");
      out.write("\t\t\t\tmouseenter : function() {\r\n");
      out.write("\t\t\t\t\t$(this).find(\"ul\").stop().slideDown(300);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tmouseleave : function() {\r\n");
      out.write("\t\t\t\t\t$(this).find(\"ul\").stop().slideUp(300);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div id=\"mypage-nav\">\r\n");
      out.write("\t\t<div class=\"info-area\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath() + profileImagePath );
      out.write("\" alt=\"회원아이콘\"\r\n");
      out.write("\t\t\t\tclass=\"profile-icon\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>");
      out.print(loginMember.getMemberId() );
      out.write(" 님</li>\r\n");
      out.write("\t\t\t\t<li>");
      out.print(loginMember.getMemberPoint() );
      out.write(" 포인트</li>\r\n");
      out.write("\t\t\t\t<li>팔로워 수 : <span id=\"mypage-follower\">");
      out.print(follow[1] );
      out.write("</span>명</li>\r\n");
      out.write("\t\t\t\t<li>팔로잉 수 : <span id=\"mypage-following\">");
      out.print(follow[0] );
      out.write("</span>명</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"bell-setting-btn\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/bell-off.png\" alt=\"알람벨버튼\"></a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/mypage\"\tclass=\"bell-setting-btn\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/setting-off.png\" alt=\"세팅버튼\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"mypage-btn-list\">\r\n");
      out.write("\t\t\t<a href=\"#\">학습노트 관리</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/onstudyList\">온스터디 내역</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/logout\">로그아웃</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"shadow\"></div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//좌측 마이페이지 버튼 클릭시 이벤트\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\".mypage-btn>img\").on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\t$(\"#mypage-nav\").fadeIn(300);\r\n");
      out.write("\t\t\t\t\t$(\"#shadow\").show(0);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#shadow\").on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\t$(this).hide(0);\r\n");
      out.write("\t\t\t\t\t$(\"#mypage-nav\").fadeOut(300);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 미니버튼 호버시 색상변경 이벤트\r\n");
      out.write("\t\t\t$(\".bell-setting-btn\").on(\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tmouseenter : function() {\r\n");
      out.write("\t\t\t\t\t\t\tvar renameImg = $(this).find(\"img\").prop(\"src\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.replace(\"-off.\", \"-on.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(this).find(\"img\").prop(\"src\", renameImg);\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tmouseleave : function() {\r\n");
      out.write("\t\t\t\t\t\t\tvar renameImg = $(this).find(\"img\").prop(\"src\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.replace(\"-on.\", \"-off.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(this).find(\"img\").prop(\"src\", renameImg);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"button-top\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"top-btn\">TOP</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction scrollFunction() {\r\n");
      out.write("\t\t\tif ($(window).scrollTop() >= 200) {\r\n");
      out.write("\t\t\t\t$('#button-top').show(0);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#button-top').hide(0);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tscrollFunction();\r\n");
      out.write("\t\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t\t\tscrollFunction();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('#button-top').on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\t$('html,body').stop().animate({\r\n");
      out.write("\t\t\t\t\t\tscrollTop : 0\r\n");
      out.write("\t\t\t\t\t}, 600);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <div id=\"container\" style=\"color:#333333;\"> <!-- container 시작 div -->\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          <div class=\"container-fluid container\">\r\n");
      out.write("\r\n");
      out.write("            <!-- 타이틀 -->\r\n");
      out.write("            <div class=\"row\"> \r\n");
      out.write("              <div class=\"col-md-12\">\r\n");
      out.write("                <div class=\"page-header\">\r\n");
      out.write("                  검색 결과\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 검색 -->\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-12 onstudy-main-search\">\r\n");
      out.write("                <form method=\"get\" action=\"../onstudy/searchList\">\r\n");
      out.write("                  <input type=\"text\" id=\"search-keyword\" name=\"search-keyword\" class=\"col-sm-10\" value=\"");
      out.print(searchKeyword );
      out.write("\" placeholder=\"검색할 단어를 입력하세요\">\r\n");
      out.write("                  <button class=\"btn btn-outline-secondary more-btn\" id=\"search-btn\" type=\"submit\">검색</button><br>\r\n");
      out.write("                  <a class=\"option-detail-btn\" href=\"#option-detail\"><b>세부 옵션 설정 <span id=\"option-detail-icon\">▼</span></b></a><br>\r\n");
      out.write("                  <div id=\"option-detail\">\r\n");
      out.write("                    <b>- 카테고리</b><br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn-category btn-group-toggle\" id=\"onstudy-category\" name=\"onstudy-category\" data-toggle=\"buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"영어\"> 영어 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"중국어\"> 중국어 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"일본어\"> 일본어 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"스페인어\"> 스페인어 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"프랑스어\"> 프랑스어 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"한자\"> 한자 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"JAVA\"> JAVA \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"C언어\"> C언어 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"PYTHON\"> PYTHON \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"자바스크립트\"> 자바스크립트 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"정보처리기사\"> 정보처리기사 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"수학\"> 수학 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"한국사\"> 한국사 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"과학\"> 과학 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"사회\"> 사회 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"공무원\"> 공무원 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"임용고시\"> 임용고시 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"수능\"> 수능 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"전산세무\"> 전산세무 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-sm btn-outline-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"onstudy-category\" value=\"기타 등등\"> 기타 등등 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <b>- 기간설정</b><br>\r\n");
      out.write("                    <input type=\"date\" name=\"search-start\" value=\"");
      out.print(searchStart );
      out.write("\">\r\n");
      out.write("                    ~\r\n");
      out.write("                    <input type=\"date\" name=\"search-end\" value=\"");
      out.print(searchEnd);
      out.write("\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </form>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <!-- 온스터디 -->\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-12\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-md-12\">\r\n");
      out.write("                    <hr>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                ");
for(Onstudy onstudy : sList) { 
      out.write("\r\n");
      out.write("                      <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                          <img class=\"mb-3\" alt=\"온스타일 이미지\" style=\"height:200px\"\r\n");
      out.write("                          \tsrc=\"");
      out.print( onstudy.getThumbnail() != null ? request.getContextPath() + "/resources/onstudyThumbnails/" + onstudy.getThumbnail() : request.getContextPath() + "/resources/onstudyThumbnails/noimage.png" );
      out.write("\" />\r\n");
      out.write("                          <div class=\"card-block\">\r\n");
      out.write("                            <h5 class=\"card-title\">\r\n");
      out.write("                        ");
      out.print(onstudy.getOnstudyTitle() );
      out.write("\r\n");
      out.write("                            </h5>\r\n");
      out.write("                            <p class=\"card-text\">\r\n");
      out.write("                              <span class=\"badge badge-pill badge-secondary\">#");
      out.print(onstudy.getCategoryNm() );
      out.write("</span><br>\r\n");
      out.write("                              <b>모집 마감</b>&nbsp;&nbsp;");
      out.print(onstudy.getOnstudyDeadlineDt() );
      out.write("<br>\r\n");
      out.write("                              <b>참여 기간</b>&nbsp;&nbsp;");
      out.print(onstudy.getOnstudyStartDt() );
      out.write(' ');
      out.write('~');
      out.write(' ');
      out.print(onstudy.getOnstudyEndDt() );
      out.write(' ');
      out.write('(');
      out.print(onstudy.getOnstudyWeeks() );
      out.write("주)<br>\r\n");
      out.write("                              <b>인증 횟수</b>&nbsp;&nbsp;주 ");
      out.print(onstudy.getOnstudyCertifyCount() );
      out.write("회<br>\r\n");
      out.write("                              <b>참 가 비</b>&nbsp;&nbsp;");
      out.print(onstudy.getOnstudyFee() );
      out.write("<br>\r\n");
      out.write("                              <a class=\"btn btn-outline-secondary more-btn\" href=\"../onstudy/detail?oNo=");
      out.print(onstudy.getOnstudyNo() );
      out.write("\" style=\"float: right;\">자세히보기</a>\r\n");
      out.write("                            </p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("             \t");
} 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <br><br>\r\n");
      out.write("        <!-- 페이징바 -->\r\n");
      out.write("\t        <div style=\"clear: both;\">\r\n");
      out.write("\t            <ul class=\"pagination\">\r\n");
      out.write("\t            \t");
 if(currentPage > 1) { 
      out.write("\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                \t<!-- 맨 처음으로(<<) -->\r\n");
      out.write("\t                    <a class=\"page-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/onstudy/searchList?currentPage=1\">&lt;&lt;</a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                \r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                \t<!-- 이전으로(<) -->\r\n");
      out.write("                   \t\t<a class=\"page-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/onstudy/searchList?currentPage=");
      out.print( currentPage-1 );
      out.write("\">&lt;</a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                ");
 } 
      out.write("\r\n");
      out.write("\t                \r\n");
      out.write("\t                <!-- 페이지 목록 -->\r\n");
      out.write("\t                ");
 for(int p = startPage; p <= endPage; p++){ 
      out.write("\r\n");
      out.write("\t                \t");
 if(p == currentPage) { 
      out.write("\r\n");
      out.write("\t\t                <li>\r\n");
      out.write("\t\t                    <a class=\"page-link\">");
      out.print( p );
      out.write("</a>\r\n");
      out.write("\t\t                </li>\r\n");
      out.write("\t                \t");
 } else{ 
      out.write("\r\n");
      out.write("                \t\t<li>\r\n");
      out.write("\t                    \t<a class=\"page-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/onstudy/searchList?currentPage=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>              \r\n");
      out.write("\t                \t</li>\r\n");
      out.write("\t                \t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t                \r\n");
      out.write("\t                <!-- 다음 페이지로(>) -->\r\n");
      out.write("\t                ");
 if(currentPage < maxPage){ 
      out.write("\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <a class=\"page-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/onstudy/searchList?currentPage=");
      out.print( currentPage+1 );
      out.write("\">&gt;</a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                \r\n");
      out.write("\t                \r\n");
      out.write("\t                \r\n");
      out.write("\t                <!-- 맨 끝으로(>>) -->\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <a class=\"page-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/onstudy/searchList?currentPage=");
      out.print( maxPage );
      out.write("\">&gt;&gt;</a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                ");
 }
      out.write("\r\n");
      out.write("\t                \r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>              <br><br>\r\n");
      out.write("\r\n");
      out.write("        </div> <!-- container 종료 div -->\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("          // 팔로우 버튼 클릭시 이벤트\r\n");
      out.write("          $(function(){\r\n");
      out.write("            var optionToggle = 0;\r\n");
      out.write("            $(\".follow-btn\").on({\r\n");
      out.write("              click : function(){\r\n");
      out.write("                if(followToggle==0){\r\n");
      out.write("                  var count = $(\".follower-count dt\").html();\r\n");
      out.write("                  count++;\r\n");
      out.write("                  $(\".follower-count dt\").html(count);\r\n");
      out.write("                  followToggle = 1;\r\n");
      out.write("                  $(\".follow-btn\").html(\"팔로우 취소\");\r\n");
      out.write("                }else{\r\n");
      out.write("                  var count = $(\".follower-count dt\").html();\r\n");
      out.write("                  count--;\r\n");
      out.write("                  $(\".follower-count dt\").html(count);\r\n");
      out.write("                  followToggle = 0;\r\n");
      out.write("                  $(\".follow-btn\").html(\"팔로우\");\r\n");
      out.write("                }\r\n");
      out.write("              }\r\n");
      out.write("            });\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("            // 세부 옵션 클릭시 이벤트\r\n");
      out.write("            $(\".option-detail-btn\").on({\r\n");
      out.write("              click : function(){\r\n");
      out.write("                if(optionToggle == 0){\r\n");
      out.write("                  var count = $(\"#option-detail-icon\").html(\"▲\");\r\n");
      out.write("                  $(this).css(\"color\", \"#f15a25\");\r\n");
      out.write("                  optionToggle = 1;\r\n");
      out.write("                }else{\r\n");
      out.write("                  var count = $(\"#option-detail-icon\").html(\"▼\");\r\n");
      out.write("                  $(this).css(\"color\", \"#333333\");\r\n");
      out.write("                  optionToggle = 0;\r\n");
      out.write("                }\r\n");
      out.write("              }\r\n");
      out.write("            });\r\n");
      out.write("          });\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"button-top\">\r\n");
      out.write("          <button type=\"button\" class=\"top-btn\">TOP</button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("        \r\n");
      out.write("        $(function(){\r\n");
      out.write("            var optionToggle = 0;\r\n");
      out.write("            $(\".follow-btn\").on({\r\n");
      out.write("              click : function(){\r\n");
      out.write("                if(followToggle==0){\r\n");
      out.write("                  var count = $(\".follower-count dt\").html();\r\n");
      out.write("                  count++;\r\n");
      out.write("                  $(\".follower-count dt\").html(count);\r\n");
      out.write("                  followToggle = 1;\r\n");
      out.write("                  $(\".follow-btn\").html(\"팔로우 취소\");\r\n");
      out.write("                }else{\r\n");
      out.write("                  var count = $(\".follower-count dt\").html();\r\n");
      out.write("                  count--;\r\n");
      out.write("                  $(\".follower-count dt\").html(count);\r\n");
      out.write("                  followToggle = 0;\r\n");
      out.write("                  $(\".follow-btn\").html(\"팔로우\");\r\n");
      out.write("                }\r\n");
      out.write("              }\r\n");
      out.write("            });\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("            // 세부 옵션 클릭시 이벤트\r\n");
      out.write("            $(\".option-detail-btn\").on({\r\n");
      out.write("              click : function(){\r\n");
      out.write("                if(optionToggle == 0){\r\n");
      out.write("                  var count = $(\"#option-detail-icon\").html(\"▲\");\r\n");
      out.write("                  $(this).css(\"color\", \"#f15a25\");\r\n");
      out.write("                  optionToggle = 1;\r\n");
      out.write("                }else{\r\n");
      out.write("                  var count = $(\"#option-detail-icon\").html(\"▼\");\r\n");
      out.write("                  $(this).css(\"color\", \"#333333\");\r\n");
      out.write("                  optionToggle = 0;\r\n");
      out.write("                }\r\n");
      out.write("              }\r\n");
      out.write("            });\r\n");
      out.write("          \r\n");
      out.write("          $(\"#search-category\").on({\r\n");
      out.write("          \tclick : function(){\r\n");
      out.write("        \t\t$('input[name=\"search-category\"]').prop(\"chekced\");\r\n");
      out.write("          \t}\r\n");
      out.write("          \r\n");
      out.write("            });\r\n");
      out.write("         \r\n");
      out.write("   \r\n");
      out.write("      \t});\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        $.each($(\"input[name=onstudy-category]\"),function(index,item){\r\n");
      out.write("        \tif($(item).val() == \"");
      out.print(searchCategory);
      out.write("\"){\r\n");
      out.write("        \t\t$(item).prop(\"checked\", true);\r\n");
      out.write("        \t}\r\n");
      out.write("        });      \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("       </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("        <div class=\"container-fluid container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4 footer-logo-wrap\">\r\n");
      out.write("                            <img class=\"footer-logo\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/logo2-white.png\" alt=\"푸터로고\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-8\">\r\n");
      out.write("                            <p class=\"copyright\">&copy; 2020 NOKJO COMPANY. ALL RIGHTS RESERVED.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\" integrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
